### ISSUE TITLE
Birds Nest Glowstone und Redstone drop verringern

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#101]

**Comment by Grambosch** [comment]
https://github.com/BakermanLP/ProjectRET-AoT/pull/113

**Comment by BakermanLP** [comment]
Ist noch die Frage offen, ob der oder der andere Pull Request hier der richtigere ist :)

**Comment by Grambosch** [comment]
Grr. Hat der beides zusammengepackt sry. Beide gleich , wollte eigentlich die nur getrennt liefern

**Comment by BakermanLP** [comment]
Nach Anpassungen von Grambosch .. CLOSE
