### ISSUE TITLE
Rezept 8 Logs -> 4 Chests

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#102]
Aus 8 Logs sollen gesamt 4 Chests werden mit Oredict Input
x x x
x . x
x x x
Daraus sollen 4 Standard Vanilla Chests werden.

**Comment by DerOliDE** [comment]
Auch hier Skript copy n' paste aus Shattered World, angepasst, getestet und als pull request vorbereitet.

**Comment by BakermanLP** [comment]
Doppel Danke 😀

**Comment by DerOliDE** [comment]
Nix zu danken, Arbeit die schonmal erledigt wurde muss man ja nicht doppelt machen :)
