### ISSUE TITLE
DRINGEND..

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#104]
Von Botania die Shards bitte rausnehmen.  "Shard of Laputa". Hebt große Gebiete aus der Erde und lässt sie als schwebende Inseln erscheinen.

**Comment by DerOliDE** [comment]
Skript copy n' paste aus Shattered World, angepasst, getestet und als pull request vorbereitet.

**Comment by BakermanLP** [comment]
Danke
