### ISSUE TITLE
Gradle buildscript fürs Modpack

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#106]
Ich hatte im Rahmen der letzten Shattered World updates bissi mit Gradle rumgespielt, um mir ein flexibles buildscript zu basteln, welches mir client und server instanzen automatisch für dev und publish zusammenbastelt. Das ist z.Z. noch starr auf client/server beschränkt aber ich bin dabei das so flexible zu gestallten, dass man beliebige client und server instanzen konfigurieren kann. Im Falle Shattered World wäre das bspw. anstatt nur server noch in Forge und Thermos zu unterteilen und in AoT könnte man damit auch automatisiert clients und server für die jeweiligen Epochen generieren lassen.

Wenn interesse für AoT besteht liese es sich übernehmen, die Konfiguration was wohin wandert läuft über die [modpack.json](https://github.com/combak/ShatteredWorld/blob/master/modpack.json).

**Comment by BakermanLP** [comment]
Das habe ich mit einem Bash Skript geregelt.

Eventuell komme ich darauf zurück

**Comment by DerOliDE** [comment]
Ja, hatte ich vorher auch, der Gedanke war halt, dass es überall läuft, egal was für ein OS. :)
