### ISSUE TITLE
Bedrock Ores

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#107]
Sangar war fleißig und hat wieder eine interessante Mod auf die Beine gestellt, die vielleicht noch hier rein passen könnte.

https://www.youtube.com/watch?v=hYSFQ7XTE5w

**Comment by BakermanLP** [comment]
Hat er mir direkt als PM geschrieben. Klingt super. Jemand Lust zu Testen
und zu integrieren? Sollte keine allzu große Sache sein

**Comment by DerOliDE** [comment]
Ich schaue es mir mal Richtung WE an.

**Comment by DerOliDE** [comment]
Erste Ladung Erze ist drin, überwiegend die Ader Einstellungen übernommen, nur an der Gewichtung der Erze etwas gespielt.

**Comment by BakermanLP** [comment]
Sieht erst Mal super aus. Werde ich am Montag probieren.

**Comment by BakermanLP** [comment]
Ist nun im aktuellen Release 0.8.3

**Comment by DerOliDE** [comment]
Die Erze sollten ja für Phase 1 ausreichen?

**Comment by BakermanLP** [comment]
Müssen wir noch kontrollieren, ob sie auch erzeugt werden. Aber laut Config
sieht es gut aus

Oliver <notifications@github.com> schrieb am Mo., 23. Okt. 2017, 16:09:

**Comment by DerOliDE** [comment]
Hatten die Config gestern testweise schon auf Mining eingespielt, sah soweit gut aus, nur die Menge könnte man noch halbieren aber können wir ja nochmal heute Abend drüber schauen.

**Comment by DerOliDE** [comment]
TODO Adern/Menge halbieren.

**Comment by DerOliDE** [comment]
@BakermanLP Zum nächsten Update bitte die Mining Welt reseten, damit ich schauen kann, ob die Menge jetzt hin haut.

**Comment by DerOliDE** [comment]
Gibt es neue Erze die als Bedrock Ore in Kapitel 2 benötigt werden?

**Comment by BakermanLP** [comment]
Es sollten laut Config alle Erze inkl Age 4 vorhanden sein, manche werden aber nicht generiert, da es die Erze im Pack (z.B. Ruby) noch nicht gibt.

**Comment by DerOliDE** [comment]
Schließe ich auch mal ab, sofern noch neue Erze gebraucht werden, kann man das hier ja wiedereröffnen.
