### ISSUE TITLE
Antrag

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#108]
Hiermit beantrage ich..boah klingt das doof

Ich wünsche mir das die Erze ihre Form nur über die Tinkerschmelze ändern können. Nuggets zu Barren. Ansonsten ist man sehr schnell mit ein bisschen Sieben beim Water strainer. den Hinstellen und erst mal 2 stunden Kaffee trinken gehen...geht mit perönlich zu einfach

**Comment by BakermanLP** [comment]
Wenn man für dir späteren Ages eine andere Methode findet, dann wäre das für mich in Ordnung.

**Comment by Grambosch** [comment]
Mit Tinker I/O ist da kein Flaschenhals mehr . das ist so schnell auch beim schmelzen

**Comment by BakermanLP** [comment]
Flaschenhals nicht, aber wenn jeder so ein "Gear O Mat" oder solche Geschichten aufbaut, dann zehrt das wieder an der Performance, da sowas jeder haben möchte. Das waren meine 2 Cents, warum ich es einfach gehalten hatte.
