### ISSUE TITLE
The one Probe

### ISSUE THREAD

**Issue by Grambosch** [BakermanLP/ProjectRET-AoT#110]
Wird der Mod eigentlich noch für irgendwas anderes gebraucht ? 
So was wie Waila scherint ja drauf zu sein

**Comment by BakermanLP** [comment]
Das ist genau der Ersatz für Waila.
Lasst mich das genauer formulieren, wir nutzen hier "The one probe" als Waila Ersatz, ohne das eigentlich Item benutzen zu müssen.

**Comment by Grambosch** [comment]
Ah sry . Kannte das nur mit dem Helm Attachment.
