### ISSUE TITLE
Server Crash Compressed Skeleton

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#111]
Compressed Skeleton (Ex Compressum) mit Staff + Petal Dust/Rose's Thorns (Roots 2) gekillt und der Server ist mit dieser Meldung gecrasht:

https://gist.github.com/DerOli82/96346924a5480e2c73e5f62ba7af0b8b

**Comment by DerOliDE** [comment]
Korrektur die sind aus Ex Compressum

**Comment by DerOliDE** [comment]
Ist reproduzierbar.

**Comment by BakermanLP** [comment]
Ich wollte die compressed Mobs rausnehmen, gefallen mir sowieso nicht.

Am Mo., 2. Okt. 2017, 16:45 schrieb Oliver <notifications@github.com>:

**Comment by Grambosch** [comment]
Problerrm ist hier wohl ne Kombination aus Roots/Ex Compressum. Hab da eh schon die nervigsten entfernt
