### ISSUE TITLE
Spieler Inventar wird nicht mit Transferiert

### ISSUE THREAD

**Issue by Nedelosk** [BakermanLP/ProjectRET-AoT#125]
Beim wechseln der Server wird das Inventar des Spielers nicht mit transferiert.
## North:
![2017-10-11_18 38 47](https://user-images.githubusercontent.com/10259214/31453781-8b0463e4-aeb3-11e7-8ced-5c7257808ca8.png)
## Lobby:
![2017-10-11_18 39 03](https://user-images.githubusercontent.com/10259214/31453782-8b3a5422-aeb3-11e7-9e74-09815f648db8.png)

**Comment by BakermanLP** [comment]
Fehlermeldung laut Server:
```
lobby/logs/fml-server-latest.log:[18:36:38] [Server thread/WARN] [invsync/]: Loading player Nedelosk (6b93bbcf-727d-4bee-82d0-d2e3a4907567) failed because the previous server did not finish writing the data in time. Will synchronize anyway!
```
Ist bisher zum ersten Mal passiert. Ich werde mir das genauer ansehen.

**Comment by hellamie** [comment]
beim Umloggen von Lobby auf NOrth (weil north down war) sind aus meinem Inventar ein paar sachen verschwunden..aber dafür habe ich meine Picke Doppelt..

**Comment by hellamie** [comment]
War gestern auf Mining..(meiN Rucksack wurde nicht mitgenommen) auf dem Rückweg war alles aus der Miningwelt weg und mein normals Inventar wieder da
  Wenn ich wieder in der Miningwelt bin habe ich das "miningInventar"

**Comment by DerOliDE** [comment]
Ich bin mal so frei die Inv Sync Probleme zu schließen, gab nach der Änderung übers Wochenende keine Probleme mehr damit.
