### ISSUE TITLE
[JEI] Decocraft Rezepte werden nicht angezeigt

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#126]
Im JEI werden nur 4 Rezepte für Decocraft angezeigt. Es fehlt vor allem das Rezept für die Decobench, die anderen Dinge, welche über die Bench hergestellt werden, sind ja nicht zwingend im JEI nötig.

PS: Die Decobench ist craftbar, es werden nur die Rezepte nicht angezeigt.

**Comment by BakermanLP** [comment]
Wird in 1.12.2er Version funktionieren

**Comment by DerOliDE** [comment]
Funktioniert in der 1.12.2 - closed.
