### ISSUE TITLE
The Probe Overlay wird von Effekt Overlay überdeckt

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#127]
kA welche Mod die Effekte (Potions) als Overlay anzeigt aber es überdeckt das Overlay von The Probe

![screenshot_20171013_174155](https://user-images.githubusercontent.com/5699429/31554465-eeea2f48-b03d-11e7-9e16-d5d5f9cd8dda.png)

**Comment by BakermanLP** [comment]
Soll ich das Potion Overlay ausschalten oder verschieben?

Für mich als Info: config/dsurround/dsurround.cfg

**Comment by DerOliDE** [comment]
Wenn wir unten links nix haben und es möglich ist, dann von unten links aufsteigend nach oben.

**Comment by DerOliDE** [comment]
Hab mal bissi rumgespielt und mir persönlich gefällt es unter der Map recht gut, da stört es nicht aber man hat es noch recht gut im Blick.
![hud](https://user-images.githubusercontent.com/5699429/32698378-0954d1e8-c7a5-11e7-8dc1-128083caf238.png)

Config:
```
"potion hud" {
    # Disables Vanilla and Dynamic Surroundings potion HUD [default: false]
    B:"No Potion HUD"=false

    # Enable display of potion icons in display [default: true]
    B:Enable=true

    # Transparency factor for icons (higher more solid) [range: 0.0 ~ 1.0, default: 0.75]
    S:Transparency=0.75

    # Size scale of icons (lower is smaller) [range: 0.0 ~ 1.0, default: 0.75]
    S:"Display Scale"=0.6

    # Area of the display the Potion HUD is displayed (0 upper left, 1 upper right) [range: 0 ~ 1, default: 0]
    I:"HUD Location"=1

    # Offset from top of screen [range: 0 ~ 2147483647, default: 5]
    I:"Vertical Offset"=100

    # Offset from left side of screen [range: 0 ~ 2147483647, default: 5]
    I:"Horizontal Offset"=5
}
```
