### ISSUE TITLE
Spieler Inventar wird auf früheren Stand zurückgesetzt

### ISSUE THREAD

**Issue by Bekador** [BakermanLP/ProjectRET-AoT#129]
Mein Inventar auf Nord wurde gerade auf einen früheren Inhalt zurückgesetzt.

**Comment by DerOliDE** [comment]
Kann daran liegen, dass der Server gehängt hat (siehe https://github.com/BakermanLP/ProjectRET-AoT/issues/128) und ich ihn abschießen musste, sprich die Welt wurde u.U. nicht gespeichert oder nicht richtig mit der DB synchronisiert.

**Comment by DerOliDE** [comment]
Ich bin mal so frei die Inv Sync Probleme zu schließen, gab nach der Änderung übers Wochenende keine Probleme mehr damit.
