### ISSUE TITLE
Rezept doppel Belegung

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#130]
Cow Bait (Ex Compressum) und Dough (Actually Additions) haben das selbe Rezept( 2 Wheat nebeneinander ), wodurch sich Dough nicht craften lässt.

**Comment by Grambosch** [comment]
Wooden Wrench - Wooden Hammer genau dasselbe

**Comment by BakermanLP** [comment]
Sieht gut aus, deswegen erst mal Close. Ist in der nächsten Version diese Woche enthalten

**Comment by BakermanLP** [comment]
Mist, Hammer Wrench übersehen.

**Comment by BakermanLP** [comment]
Verdammt, was ist den das mit dem Hammer und der Wrench:
```
recipes.addShaped(<chiselsandbits:wrench_wood>, [[null, <ore:plankWood>, null], [<ore:plankWood>, <ore:stickWood>, null], [null, null, <ore:stickWood>]]);
recipes.addShaped(<exnihiloadscensio:hammerwood>, [[null, <ore:plankWood>, null], [null, <ore:stickWood>, <ore:plankWood>], [<ore:stickWood>, null, null]]);
```
Das sind doch unterschiedliche "Shaped" Rezepte. Wer spielt da nicht mit?
