### ISSUE TITLE
Freischaltung new Age

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#139]
*ich habe da mal eine Idee*

Wenn die finale North Karte steht bauen wir ja das Portal zur Lobby auf den "Dorfplatz", mit ein bisschen Anfang Deko.

Mit der Claim-Mod kann man grundstücke vorprogamieren und verkaufen..wäre es ggf sinnvoll einzelne Gebiete abzustecken?. hinter zaun 1 mus das und das stehen für age 2 frei?

**Comment by BakermanLP** [comment]
Klingt nach einem Plan. Gefällt mir.

hellamie <notifications@github.com> schrieb am Mi., 18. Okt. 2017, 08:21:

**Comment by Bekador** [comment]
Vor allen Dingen wäre so auch eine vorhergehende Stadtplanung möglich und dem "Wildwuchs" der Gebäude einhalt geboten.

**Comment by hellamie** [comment]
fertige Gebäude für Age 2
- Poststelle
- Schmelze
- Bauernhof
- Gemeindezentrum
- Marktplatz
- Tarverne

**Comment by Grambosch** [comment]
Steht im Achievement Book alles drin also close
