### ISSUE TITLE
Airship

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#140]
Wir wollten gerade mal damit rumspielen..

aber das geht nicht. Wir haben ein Item (arcadia Visdenburg) genommen und wollten es setzen..nun ist der ganze Strand voll aber wir sehen nichts und können auch nichts mehr abbauen..stehen bei Bekador im "Garten".

Schade

**Comment by BakermanLP** [comment]
Das scheint daran zu liegen, dass in den Items, die man in JEI sieht unter Appearance was komisches steht.

**Comment by BakermanLP** [comment]
Da der Mod rausfliegt, kann ich den Issue hier schliessen. Oder war es andersrum?
