### ISSUE TITLE
Uncrafting Table - Kein Rezept hinterlegt

### ISSUE THREAD

**Issue by Bekador** [BakermanLP/ProjectRET-AoT#141]
Wie oben schon beschrieben ist für den Uncraftin Table kein Rezept hinterlegt, er lässt sich ergo nicht bauen.

**Comment by BakermanLP** [comment]
Das ist gewollt so. Der dient im Moment dem Debugging von Rezepten.

Bekador <notifications@github.com> schrieb am Do., 19. Okt. 2017, 15:52:
