### ISSUE TITLE
Nether, wo, wann, wie, warum?

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#142]
z.Z. scheint der Nether ja komplett deaktiviert zu sein und Nether Inseln sind in der WorldGen, soweit ich sehe, auch nicht mehr drin. Die Frage wäre nun wohin damit?

Mein Vorschlag wäre, den Nether auf dem Mining Server zu aktivieren, dann lässt er sich zusammen mit der Mining Welt reseten ohne viel Extraaufwand.

**Comment by BakermanLP** [comment]
Ui, gute Idee.

Oliver <notifications@github.com> schrieb am Do., 19. Okt. 2017, 17:44:

**Comment by BakermanLP** [comment]
Nur auf der Mining Welt sind Nether und "The End" eingeschaltet.

**Comment by DerOliDE** [comment]
Server crasht wenn man den Nether betritt 

https://gist.github.com/DerOli82/b53f8ad79c4e6b9f8f96f6bddfce6066

**Comment by BakermanLP** [comment]
Sieht auch so aus, als ob wir mit OpenTerrainGeneration eine Version zurück gehen müssten.
