### ISSUE TITLE
Bedrockores crash

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#144]
Crash-Report: https://gist.github.com/DerOli82/6f4a77bd29dfe2204f0172f604c0a6da

Hergang: Modeigene Maschine auf Bedrockore gesetzt und an Strom angeschlossen. 

Mal schauen, ob es im nächsten Update behoben wurde.

**Comment by BakermanLP** [comment]
Bei Oli gings nach dem Update. Bitte noch jemand verifizieren.

**Comment by BakermanLP** [comment]
Gerade verifiziert, geht nun ohne Probleme anscheinend. Also CLOSE

**Comment by BakermanLP** [comment]
Gerade wieder passiert:
http://paste.ubuntu.com/25803548/

**Comment by BakermanLP** [comment]
https://github.com/MightyPirates/BedrockOres/issues/47

**Comment by DerOliDE** [comment]
Issue ist bei den Piraten geschlossen und ich bekomme den Fehler auch nicht mehr reproduziert. Falls er wieder auftauchen sollte, dann Issue einfach wieder öffnen.
