### ISSUE TITLE
Nether und End über Mining Welt

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#151]

**Comment by BakermanLP** [comment]
Eventuell OpenTerrainGeneration auf v6 zurück setzen

**Comment by Grambosch** [comment]
https://github.com/BakermanLP/ProjectRET-AoT/issues/142    
Mit Verweis hierhin den alten Issue geschlossen

**Comment by BakermanLP** [comment]
Close, da in der Mining Welt Nether und The End zur Verfügung stehen.
