### ISSUE TITLE
Es existieren 2 unterschiedliche Alumite fluids

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#161]
Es gibt sowohl aus Hardcore ORE als auch aus PlusTiC Molten Alumite als Fluid. Beim Alloying hatte ich dann zwei unterschiedliche Alumite Fluids in der Schmelze, die direkt beim gießen nicht kompatible sind. Was für eine Sorte beim Alloying generiert wird scheint reiner Zufall zu sein.

Bspw. hatte ich 3 Alumite von einer Sorte und 7 von der anderen Sorte im Tank und beim gießen eines Hammerkopfes sind nur die 3 im Cast gelandet und die anderen 7 konnte man nicht hinzu gießen.

**Comment by BakermanLP** [comment]
Ich werde das Plustic abschalten.

**Comment by DerOliDE** [comment]
Kommt nur noch eine Sorte beim Alloying raus.
