### ISSUE TITLE
Questbuch

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#162]
Crafting Quest gehen nicht..er erkennt die einfach nicht..normale haben das im inventar gehen...Bitte überprüfen woran das liegen könnte.

**Comment by BakermanLP** [comment]
Ich habe hier folgenden gefunden. Eventuell muss man für die Quests den Edit Mode einfach beenden und dann sollte es gehen, laut dem Issue:
https://github.com/Funwayguy/BetterQuesting/issues/230

**Comment by hellamie** [comment]
Mit dem Befehl /bq_admin edit schaltet mann die bearbeitung aus und dann gehen auch die Quest richtig.
