### ISSUE TITLE
mystikal agricutlure

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#163]
Ich kann nicht mit der Mod starten, weil ich kein Prosperty Ore finden kann.

Nicht in der Miningwelt, noch im Strainer noch sonst wo..es wird mir auch beim Ore nicht angezeigt wo ich es finden kann.

**Comment by BakermanLP** [comment]
Ist registriert, müssen wir mal schauen, wo man das her bekommen soll.

**Comment by hellamie** [comment]
vor dem Patch habe ich unterm haus abgebaut..kann man von mir aus einach in den Strainer stopfen

**Comment by BakermanLP** [comment]
Laut Konfig werden die Ores nur im Nether und im End erzeugt. Wäre das in Ordnung?

**Comment by hellamie** [comment]
ja..nether ist ja in der mining welt..Mus nur Krokodiele acht geben

**Comment by BakermanLP** [comment]
Also das hier kann geschlossen werden, in der Mining Welt gibt es die Erze im Nether
