### ISSUE TITLE
Kapitel 1 - Balancing

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#164]
Hier mal paar Gedankengänge, die es im Discord zum Balancing gab:
- [ ] Legierungen von der Wertigkeit (Abbau Dia Level) nur bis Bronze, der Rest ab Kapitel 2.
- [x] Ex Compressum, ins zweite Kapitel verschieben.
- [ ] Strainer/Sieves ggf. die noch nicht vorkommenden Erze entfernen und drop chancen anpassen, eventuell "dummy items" wie Flint und/oder Stone Pebble hinzufügen, um die Chancen anderer drops geringer zu halten.

**Comment by BakermanLP** [comment]
Legierungen hätte ich gesagt bis Bronze und Alumite. 
Ex Compressum ins zweite Kapitel, kein Problem
Sieves und Strainer anpassen, klingt gut.

**Comment by hellamie** [comment]
Weis nicht ob es hier hin gerhört..Drop rate der Federn bei den Hühner bitte runter schrauben..die  Viecher haben ja nach 5 min keine mehr am Hintern...und ich 2 Stack in der Kiste.
