### ISSUE TITLE
Questbuch Kapitel 1

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#166]
Da müssen raus für Kapitel 2:
- "Der Schamane ..:"
- "Der sich nen Wolf tanzt"
- "Reliquary"

Anordnung der Quests umstellen, man muss immer scrollen

**Comment by hellamie** [comment]
Habe mal meine Gui auf normal gestellt( würg wie groß) und dann die Questbutten verteilt. Bitte überprüfen ob bessern.

**Comment by hellamie** [comment]
Mystikal Agriculture..

Splitten oder nicht. Beim schreiben ist mir aufgeallen das viele Items in den Questen erst später benötigt werden,.

Daher die frage Mod und Questbuch splitten in die einzelen Kapitel oder so lassen und die Leute horten zeug für Kapittel 2 schon.

**Comment by Grambosch** [comment]
Sieht fertig aus
