### ISSUE TITLE
[Animania] Salt Lick Rezept lässt sich nur mit Hardcore Ore Salt herstellen

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#173]
Keine OreDict Einträge, ich schaue mir das die Tage an.

**Comment by BakermanLP** [comment]
Sollte man beide Salzarten in die OreDict Salt:dust packen:
- hardcoreore:salt
- animania:salt
... und dann das Rezept umbauen auf Salt:dust
