### ISSUE TITLE
Der Backpack von der Mod Wearable Backpack

### ISSUE THREAD

**Issue by Kappi85** [BakermanLP/ProjectRET-AoT#176]
Der Backpack behält die Items nicht bei Server wechsel.
Die Items im Inventar bleiben.

**Comment by CD4017BE** [comment]
I denke, dass der Backpack die enthaltenen Items wahrscheinlich nicht zusammen mit dem Spieler ablegt, sondern irgendwo mod intern speichert, daher wird es natürlich auch nicht zwischen den Servern synchronisiert. Und da lässt sich vermutlich auch nicht viel dran ändern.
Solange dabei global keine Items verloren gehen oder dupliziert werden, stellt es meiner Meinung auch kein Problem dar (wäre bloß convenience).

**Comment by DerOliDE** [comment]
Wenn das der Fall ist, sollte man vielleicht noch ein Tooltip an das Item ranklatschen "Nicht Server übergreifend" oder so etwas in die Richtung, sonst haben wir dutzende deswegen unnötige Fehleranfragen.

**Comment by BakermanLP** [comment]
@CD4017BE So etwas in der Art denke ich mir auch. Deshalb habe ich für die Version heute 2 weitere Backpack Mods eingebaut. Wenn einer der beiden Mods funktioniert, dann schmeissen wir die anderen Mods einfach raus.

**Comment by BakermanLP** [comment]
Alle Backpacks raus außer Iron Backpack

**Comment by BakermanLP** [comment]
Im heutigen Client Release erledigt.
