### ISSUE TITLE
Kapitel 1 enthält CraftTweaker Skripts für nicht vorhandene Mods

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#177]
Wirft im Singleplayer massig Fehlermeldungen. Macht zwar nix, sieht aber nicht schön aus.

**Comment by BakermanLP** [comment]
Sollten alle leer sein

Oliver <notifications@github.com> schrieb am Di., 21. Nov. 2017, 17:14:

**Comment by DerOliDE** [comment]
Sind sie jedenfalls noch nicht in meiner AoT Online instance aber ich kann sie ja mal testweise zurücksetzen.

**Comment by DerOliDE** [comment]
So nochmal getestet sowohl Instanzen als auch Assets gelöscht, trotzdem sind die Dateien in AoT - Online & Kapitel 1 nicht leer.

**Comment by BakermanLP** [comment]
Habe hier einen Fehler gefunden. Version heute sollte gefixed sein.

**Comment by BakermanLP** [comment]
Erledigt mit https://github.com/BakermanLP/ProjectRET-AoT/releases/tag/v0.8.6
