### ISSUE TITLE
Testing Issue Webservice

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#178]
Issue posted by DerOli82: Wenn Ihr das lesen könnt, dann funktioniert der Webservice auf Bakers Server! :)

**Comment by DerOliDE** [comment]
Wunderbar, in der Entwicklungsumgebung funktioniert es und im MultiMC jammert er wieder rum, dass ihm eine Abhängigkeit fehlt -.-

**Comment by BakermanLP** [comment]
Wie immer 😀

Oliver <notifications@github.com> schrieb am Fr., 24. Nov. 2017, 17:38:

**Comment by DerOliDE** [comment]
aufräumen - closed
