### ISSUE TITLE
Dependencies check

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#179]
Issue posted by DerOli82: dep check außerhalb der dev umgebung

**Comment by BakermanLP** [comment]
Ui... Da kam was

ComBak-Webservices <notifications@github.com> schrieb am Mo., 27. Nov.
2017, 10:30:

**Comment by DerOliDE** [comment]
Minecraft modding ist so ein pain in the ass.... Forge blockiert den namespace zu org.apache.xxx damit deren libs nicht überschrieben werden, darum muss ich meine mitgelieferten libs in einen anderen namespace verschieben, damit die nicht blockiert werden -.-

**Comment by DerOliDE** [comment]
aufräumen - closed
