### ISSUE TITLE
Ich will testen

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#181]
Issue posted by BakermanLP: Und das soll hoffentlich jetzt gehen. Und über mehrere Zeilen mit merkwürdigen Cursor Verhalten. :-)

**Comment by BakermanLP** [comment]
Ui ... Heureka ... Funzt.

**Comment by DerOliDE** [comment]
Ich muss unbedingt noch die E-Mail Benachrichtigung beim ComBak-Webservices Account abschalten, sonst werde ich total zugespammt. :D Der Account könnte auch noch ein hübsches Bildchen vertragen, irgendeine Idee?

**Comment by BakermanLP** [comment]
Nimm vom Forum das Gamepad.

**Comment by DerOliDE** [comment]
Hast Du das vielleicht noch als einzelnes Bild? Vielleicht auch ein tick größer? Dann muss ich nicht rum schneiden, bin ja faul. :)

**Comment by BakermanLP** [comment]
http://forum.bakermanlp.de/uploads/default/original/1X/87cf94bc90affe997d577c0dcb18071e062b7dec.png

Einzige Auflösung, die ich habe in 40x40. Sollte aber theoretisch reichen

**Comment by DerOliDE** [comment]
Hauptsache ich muss nicht dran rum schneiden.

**Comment by BakermanLP** [comment]
Sieht doch gut aus, auch wenn die Grafik etwas kleiner war.

**Comment by DerOliDE** [comment]
Joa das passt schon, besser als vorher ist es auf jeden Fall. ;)
