### ISSUE TITLE
Federn reduzieren

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#182]
https://github.com/BakermanLP/ProjectRET-AoT/blob/1.11.2/config/animania.cfg#L289

        B:chickensDropFeathers=true

**Comment by Grambosch** [comment]
Steht zZ auf alle 12000 Ticks ne Feder pro Vieh. Da wir hoffentlich ein Kreaturenlimit haben sollte das passen
