### ISSUE TITLE
Gamemode auf Servern

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#187]
Auf allen Servern ist nun umgestellt worden

server.properties:
gamemode=0
force-gamemode=true

config/invsync/invsync.conf:
enableGameMode=false

Nach dem Neustart sollte das Aktiv sein.

**Comment by DerOliDE** [comment]
Mir sind keine weiteren Probleme mehr bekannt, daher closed.
