### ISSUE TITLE
Spruce Wood Tür macht Kisten Sounds

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#189]
Issue posted by TheSnowyChickens: Die Spruce Wood Tür macht beim auf und zumachen die Kisten sounds (Auf und Zu)

**Comment by BakermanLP** [comment]
Das Sound Thema habe ich auch schon beim Testen gehört.

**Comment by BakermanLP** [comment]
... Und sehet her, Bug Report aus dem Spiel heraus. Juhu!

**Comment by DerOliDE** [comment]
Alle Minecraft Doors getestet, keine macht mehr das Chest Geräusch beim öffnen oder schließen.

PS: Sowohl mit als auch ohne Dynamic Surroundings getestet
