### ISSUE TITLE
Mitspielerberechtigung

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#192]
Issue posted by Blaxard: Habe mein Grundstück geclaimt und meinen Mitspieler "wolle11" zum Admin gemacht. Er kann zwar Blöcke abbauen, Felder bearbeiten, Bäume fällen und Truhen öffnen. Aber er kann keine Blätter ernten und er kann weder auf meine Geräte zugreifen noch auf seine selbst erstellten, die in meinem Grundstück stehen.

**Comment by CD4017BE** [comment]
Also ich hab auch anderen aus meiner Gruppe Berechtigungen für mein Gebiet erteilt und bisher hatte keiner Probleme auf irgendetwas zuzugreifen. Dabei hab ich aber "member" und nicht "admin" rechte erteilt. Eventuell sind bloß die admin Rechte verbuggt.

**Comment by Sharkuns** [comment]
Bei meinem Gebiet klappt es ohne Probleme mit dem Admin Zugang , evtl. haste aus versehen wirklich an den Rechten geschraubt

**Comment by Blaxard** [comment]
Hab meinen Kollegen jetzt auch als "Member" geaddet und da geht alles! Scheint wirklich an den Admin_Rechten zu liegen. Danke euch vielmals für den Tipp!
