### ISSUE TITLE
Epic Siege Mod 

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#194]
Frage von einem Spieler: Hat der Mob HP Zugewinn ein cap oder werden die jetzt immer stärker?

Ich erinnere mich noch an das Modpack dessen Name nicht genannt werden soll, dass dort die Mobs abnormal stark wurden.

**Comment by Grambosch** [comment]
The factor by which mob health and damage multipliers will be increased when bosses are killed [range: 0.0 ~ 3.4028235E38, default: 0.1]
https://github.com/BakermanLP/ProjectRET-AoT/blob/1.11.2/config/epicsiegemod.cfg#L73-L74

**Comment by Grambosch** [comment]
https://github.com/BakermanLP/ProjectRET-AoT/commit/bf0ff60c220c9cdaeb7e50989578f95ef70a3d62

**Comment by DerOliDE** [comment]
Habe die configs auf den Server schon geändert und die ESM.dat auf north und south zurückgesetzt.
