### ISSUE TITLE
Superium Rüstung ZU Stark

### ISSUE THREAD

**Issue by XCOAnnika** [BakermanLP/ProjectRET-AoT#195]
Superium Rüstung Muss Teurer Gemacht werden um ein Angenehmes Spiel Verhältnis Zu Gewehrleisten Damit Keiner overpowert ist

**Comment by DerOliDE** [comment]
Wir hatten 8 Wochen **vor** dem Release das alles zu testen, hat sich scheinbar keiner für verantwortlich gefühlt und jetzt im nachhinein das zu ändern, wo einige Spieler schon die Rüstungen haben, wäre eine massive Benachteiligung für Spieler, die dies noch nicht erreicht haben.

**Comment by Grambosch** [comment]
Und wieder close. Das ist kein Bug und war angesprochen wie Oli sagt
