### ISSUE TITLE
RedProtect Bug 

### ISSUE THREAD

**Issue by XCOAnnika** [BakermanLP/ProjectRET-AoT#196]
Read Proteckt  erkent mich nicht mehr als besitzer des Grunstükes Da ich meinen Narmen geändert Habe

**Comment by hellamie** [comment]
soll ich dein Gebiet löschen und du setzt neu`?..

**Comment by XCOAnnika** [comment]
ja bitte aber nur das gebit air-base das andere hab ich gefixt

**Comment by hellamie** [comment]
Ein deed gelöscht anderes selber geregelt..fertig
