### ISSUE TITLE
Tradestation Mod:Mailbox

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#197]
Issue posted by Knotta: Habe versucht etwas für 4 Stacks zu verkaufen, jedoch zeigt der Katalog stattdessen an, dass es Gratis angeboten wird. Habe auch keinen Erlös bekommen (sollte es denn jemand bestellt haben. Bei Reduzierung auf 1 Stack gings ohne Probleme.

/Edit DerOli82 Issues zusammengelegt. :)
Issue posted by Knotta: die Tradestation frisst mit normalem Klick hineingelegte preise bei der festlegung des festlegung des tauschpreises. Verlust 3/4 einer Insanium Essenz!

**Comment by DerOliDE** [comment]
Kann jemand der sich mit der Trade Station bissi auskennt mal versuchen den Fehler zu reproduzieren?

**Comment by BakermanLP** [comment]
Der Mod ist vorerst draußen, deswegen hier ein Close
