### ISSUE TITLE
Tradestation @mailbox

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#199]
Issue posted by Knotta: die Tradestation frisst mit normalem Klick hineingelegte preise bei der festlegung des festlegung des tauschpreises. Verlust 3/4 einer Insanium Essenz!

**Comment by DerOliDE** [comment]
Mit thematisch passenden Issue zusammengelegt.
Siehe https://github.com/BakermanLP/ProjectRET-AoT/issues/197
