### ISSUE TITLE
Server crash durch EZ Storage und Project Table

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#200]
Crash-Report:
https://gist.github.com/DerOli82/4b6173117225dfed14f22957a6948d2c

**Comment by DerOliDE** [comment]
Der eigentliche Fehler wird von der Project Table Mod ausgelöst, welche wohl irgendwo serverseitig eine GUI Klasse eingebunden hat, was beim aufrufen des DisplayNames in der EZ Storage zum crash führt.

PS.: Project Table vorübergehend auf dem Server deaktiviert.

**Comment by DerOliDE** [comment]
Cross-Ref. https://github.com/BigXplosion/ProjectTable/issues/9

**Comment by BakermanLP** [comment]
Ich habe beide Mods auf der langfristigen Abschuss Liste. Das sind nämlich
die einzigen Mods, die wir nicht in der Hand haben, oder für 1.12.2
verfügbar sind. Würden sich auch im nächsten Zeitalter verschmerzen lassen

Oliver <notifications@github.com> schrieb am Do., 14. Dez. 2017, 17:08:

**Comment by DerOliDE** [comment]
Da Project Table raus geflogen ist, schließe ich das hier mal ab.
