### ISSUE TITLE
OneProbe Baubles Item + Compacting Storage Drawer

### ISSUE THREAD

**Issue by Lysandro** [BakermanLP/ProjectRET-AoT#201]
Nachvollzogen im Single Player:

Compacting Drawer aufstellen 2. in Beiden z.B. ein Stack Iron Nuggets

Nun das Baubles OneProb Item anlegen und mit Shift einen Drawer ansehen und anschliessend 1 Nugget entfernen. Ergebnis -> Drawer leer 63 Nuggets lost.

Fragen? Fragen!

**Comment by BakermanLP** [comment]
Das passiert nur mit The one probe im Inventar? Ohne geht es?

Lysandro <notifications@github.com> schrieb am Do., 14. Dez. 2017, 15:51:

**Comment by Lysandro** [comment]
Ich teste es daheim gerne nochmal in anderen "Konstellationen" nachgewiesen habe ich den Fall mit der Baubles Variante des OneProbeItem, angelegt im Kopfslot von Baubles.

Ohne das Item tritt es nicht auf. Habe es im Moment nur mit 64 Nuggets probiert was 7 Barren sind.

Ich frage mich nämlich im Hinterkopf folgendes:
Die Anzeige zeigt kurz 0 Blöcke, 7 Barren und 64 Nuggets dann springt sie um auf 7 Barren und 64 Nuggets -> Wenn OneProbe in Java mit Verweisen arbeitet könnte da das Problem liegen, aber das ist wieder meine Programmiererdenke ......

Wie gesagt wenn ich später Zeit finde teste ich das noch "mehrfach" aus um es einzugrenzen...

**Comment by Lysandro** [comment]
Also komplett ausgetestet es ist ein Bug der wahrscheinlich in OneProbe zu suche ist -> Debuggign fehlt noch.
Er tritt auf mit dem erweiterten Tooltip und Compacting Drawer.
Solange nicht in alle Slots (Bei Barren somit Blöcke) etwas enthalten ist führt das anzeigen des erweiterten OneProbe Tooltips (Sneak) dazu das der Inhalt entfernt wird und zwar genau dann wenn die Anzeige von 0 Blöcke X Barren X Nuggets springt auf X Barren und X Nuggets.
Ich denke das es wirklich damit zu tun hat das hier mit Referenzen gearbeitet wird und beim Anzeigen des erweiterten Tooltips von 0 auf "null" gesetzt wird :(

**Comment by BakermanLP** [comment]
Gerade getestet, wird in der 1.12.2er Version funktionieren.

**Comment by BakermanLP** [comment]
So, da wir gerade auf 1.12.2 sind und es halbwegs läuft
