### ISSUE TITLE
Surfur Rezept / Mystical Agriculture

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#202]
Issue posted by TheSnowyChickens: Die Surfur seeds von M.A. brauchen zum herstellen das surfur von "Hardcore Ores" (sollte das gewesen sein :D) und das bekommt man nur von den Sulfur essencen und nicht anders (laut JEI). Ich bitte um einen OreDic eintrag bei dem rezept, danke. :)

**Comment by TheSnowyChickens** [comment]
Ich bin echt dumm... Ich schreib "Surfur" ich mein aber "Sulfur" xD
Ihr könnt ja Title ändern, da dies ja von minecraft aus geschrieben ist, kann ich es nicht ändern.

**Comment by Grambosch** [comment]
Sulfur kommt erst später

**Comment by hellamie** [comment]
age 2
