### ISSUE TITLE
bug oder feature, viele blöcke lassen sich nicht (mehr) chiseln

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#206]
Issue posted by _Zeist_: Darunter Iron, Bronze, Charcoal, Coal, Copper, Diamond, Electrum, Emerald, Invar, Lapis, Steel und Tin

**Comment by BakermanLP** [comment]
Chisel war ein Update, laut changelog eher ein Bugfix Release

**Comment by TheSnowyChickens** [comment]
Muss ein bug sein, denn die gechiselten Blöcke gibt es ja noch in JEI, nur halt nicht mehr im Chisel selbst.

**Comment by DerOliDE** [comment]
Mod Updates gibt es nur noch für die 1.12.2. In Kapitel 3 nochmal testen.

**Comment by DerOliDE** [comment]
Es sind zwar nicht mehr alle mit dabei, aber die Blöcke, welche im JEI als chiselbar angezeigt werden bspw. Diamond, Coal, Charcoal oder Emerald lassen sich wieder chiseln, Die Metalle scheint es aber nicht mehr zu geben.
