### ISSUE TITLE
Einloggen auf Server nicht möglich

### ISSUE THREAD

**Issue by Sharkuns** [BakermanLP/ProjectRET-AoT#207]
Im mom ist das Einloggen auf den Server nicht möglich , evtl. betrifft es nur Süd und Lobby da laut Anzeige 5 drauf sind und ich auf Süd normal spiele !

Man bekommt einfach einen Disconnect reingeworfen ohne weitere Fehlermeldung.

**Comment by DerOliDE** [comment]
Erledigt
