### ISSUE TITLE
Drawer ohne Tape und Tool Abbaubar

### ISSUE THREAD

**Issue by Sharkuns** [BakermanLP/ProjectRET-AoT#210]
Hi ich kann die Drawer einfach mit leerer Hand und geduckt Rechtsklick, ohne Tape zu nutzen, abbauen und wo anders hinsetzen.
Geht bei 1 fach und 4 Fach Drawern die gefüllt sind und Locket und mit Anzahl versehen sind. 2 fach nicht getestet.

Es geht nicht jedes mal ab und an macht er auch das auf, was er dabei machen sollte und zwar den Inhalt zum erweitern der Drawer mit den upgrades !!!

Edit : Man kann auch obwohl die Drawer Locket sind, andere Mats rein tun wenn sie auf 0 sind. ohne es zuvor zu löschen

**Comment by JuliusFreudenberger** [comment]
Zu Edit:
Manuell ist das gewollt, nur automatisch lassen sich leere, gelockte Slots nicht füllen.

**Comment by DerOliDE** [comment]
Kein Bug, sondern ein Feature, nennt sich "Carry On". Was aber wohl dabei passieren kann, ich konnte es noch nicht reproduzieren, ist dass der Inhalt nicht korrekt "mitgetragen" wird, was imho ein Grund wäre die Drawer auf die Blacklist zu setzen.

PS: Um an die Upgrades im Drawer zu kommen, muss die Carry On Tastenbelegung geändert werden, die ist default auf shift.

**Comment by JuliusFreudenberger** [comment]
Ich würde Drawer sowieso auf die Blacklist setzen, da das Tape dann unnötig wird.
Und das macht für mich den Reiz am Drawer transportieren aus.

**Comment by Sharkuns** [comment]
Was könnte man dann als alternative für die Ersten Ages nehmen ?

Was mir auch aufgefallen ist , ka obs nur ein Anzeige Bug ist, das ab und an das Bild vom Inhalt und auch die Anzahl verschwindet und erst nach erneutem reinlegen es wieder angezeigt wird

**Comment by JuliusFreudenberger** [comment]
Alternative für das Transportieren von Drawern?
Einfach mit Tape zu kleben und abbauen, so wie man es ohne Carry on machen würde.

**Comment by Sharkuns** [comment]
@JuliusFreudenberger 
Ich meinte alternative für die Drawer, da Oli sie ja evtl. auf die Blacklist setzen möchte.

**Comment by DerOliDE** [comment]
@Sharkuns Nicht die Drawer Mod kommt auf die Blacklist, sondern die Drawer kommen auf die Carry On Blacklist, damit man sie nicht mehr hochheben kann.

**Comment by Sharkuns** [comment]
ok , dann hab ich das falsch verstanden ^^
