### ISSUE TITLE
Age 2

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#214]
Was ist noch zu tun 

- [x] Questbuch

- [x] Mor Wands auf RF umstellen

- [x] Achivment Book

- [x] Achivements freischaltung age 3

**Comment by CD4017BE** [comment]
Ich pack meine eigene ToDo Liste auch mal hier rein:
- [ ] RedProtect Adapter testen und ggf. fixen
- [x] InductiveLogistics config: Pipes auf ultra performance freundlich umstellen (#220)

**Comment by DerOliDE** [comment]
NotEnoughWands habe ich heute erledigt. (https://github.com/BakermanLP/ProjectRET-AoT/issues/208)

**Comment by BakermanLP** [comment]
@DerOli82 Kannst du das alte Questbuch wieder herstellen und das erweiterte Questbuch in folgenden Ordner legen?
Kapitel2/config/betterquesting/
Dann wären im ersten Kapitel nur die Quests des ersten Kapitels, im Zweiten dann die vom ersten und zweiten Kapitel.

**Comment by hellamie** [comment]
Freischaltung age 3

- [x] Bahnhof mit Machinen und mindestens einer Zuglinie (128 Blöcke) einigt euch auf einen größe


- [x]  Observatorium/Planetarium

- [x] Elektrisches Licht in der Stadt und passender Stromquelle

- [x] Botanischer Garten mit Runenkreis (Botania, Roots)

**Comment by DerOliDE** [comment]
Age 2 läuft, daher auch hier mal closed :)
