### ISSUE TITLE
Mail Mod Server Crash

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#217]
South ist abgeschmiert:
https://gist.github.com/DerOli82/622d57637b5c689af0f3fb8aa54aaba5

**Comment by lordjoda** [comment]
Der Crash muss durch ein Problem ausgelöst worden sein, das im Log etwas weiter oben stehen müsste. Das Problem: Wenn die Datenbank (warum auch immer) streikt macht es keinen sinn irgendwie weiter zu arbeiten. Daher hab ich noch keinen "best case" gefunden wie ich damit umgehe...

**Comment by DerOliDE** [comment]
Ergänzend:
https://gist.github.com/DerOli82/a121859d1abcccd25ce3f4e3ab25fe56

/Edit
https://mariadb.com/kb/en/library/migrating-from-mysql-mariadb-server-closing-client-connections-unexpectedly/

**Comment by lordjoda** [comment]
grr.. ja wurde zu lange nicht genutzt => connection geschlossen. Ich dachte ich hätte da nen check eingebaut. Fehlte wohl...
Übernächste Woche mach ich das (oder falls ich mal ne Auszeit brauche ;) )

**Comment by DerOliDE** [comment]
Gab es da in Java 8 nicht ne schöne Variante mit try resources für solche Fälle?

**Comment by DerOliDE** [comment]
Der Fehler scheint mit der aktuellen Version nicht mehr aufgetreten zu sein, daher schließe ich das hier mal ab.
