### ISSUE TITLE
Actuali Editions 

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#218]
Es gibt einen Linse die heist Lense of Detonation..

Die schießt mit hilfe des Atomic recunstructor einen Laser strahl der am Ende eine Explosion verursacht. Umgeht das Red Protekt??? Wollen wir das`??? kann man die Funktion ausschalten, Ich glaube man braucht sie zum Craften von anderen Dingen noch.

**Comment by DerOliDE** [comment]
Der Laser verwandelt, soweit mir bekannt ist, nur die Materialien, welche in den Strahl geworfen werden. Das sollte für RedProtect nicht relevant sein.

**Comment by DerOliDE** [comment]
Ach hab das mit der Lens übersehen, zu wenig Kaffee, vergesst meinen Einwurf. :-S

**Comment by hellamie** [comment]
MAcht keinen Schaden gestestet

**Comment by DerOliDE** [comment]
Getestet, es gibt generell keinen Blockschaden.
