### ISSUE TITLE
Mystical Agriculture Config asyncron Client Server

### ISSUE THREAD

**Issue by michaelbaecker** [BakermanLP/ProjectRET-AoT#225]
Am Client ist eine falsche mysticalagriculture.cfg Datei. Wird im nächsten Patch behoben.

**Comment by BakermanLP** [comment]
Wird mit folgendem Commit behoben:
https://github.com/BakermanLP/ProjectRET-AoT/commit/9b3d48961effff027807b190a2e13a21c1eafac2

**Comment by DerOliDE** [comment]
Ist ja hier gefixt und im Client liegt die selbe Datei also mal closed :)
