### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#229]
Ka. ob ihr da was machen könnt, oder ob das tiefer in die materie geht.

Abbauen einer Resonant Speicher Zelle mit Crescent Hammer (Shift + rechtsklick)

[crash-2018-03-02_21.12.36-client.txt](https://github.com/BakermanLP/ProjectRET-AoT/files/1776448/crash-2018-03-02_21.12.36-client.txt)

**Comment by DerOliDE** [comment]
Tritt bei mir nach dem heutigen Update nicht mehr auf, Resonant Engery Cell in unterschiedlichen Ladezustanden mit dem Cresent Hammer abgebaut und nix ist passiert.

**Comment by TheSnowyChickens** [comment]
Sehr gut, GJ.
