### ISSUE TITLE
Falscher Loot bei Immersive Häusern Crates

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#230]
Der Title sagt es eig. schon, in Immersive Häusern spawnt noch falsches Loot, das sich (Bei Nuggets z.B.) net umwandeln lässt. 

![2018-03-05_19 04 51](https://user-images.githubusercontent.com/29357962/36991500-20338970-20a8-11e8-93b6-226683601d25.png)

**Comment by hellamie** [comment]
Schmeiß die Nuggets in die schmelze und schon werden sie richtig :)

**Comment by TheSnowyChickens** [comment]
Geht ja eben nicht, Drawer auch net. Die haben nur 2 Rezepte und keins davon ist ein einschmelz rezept.

**Comment by BakermanLP** [comment]
Ich habe da auf den Loot nicht so ohne weiteres einen Einfluss darauf, da das im Mod selber verdrahtet ist. Wenn sich da jemand berufen fühlt ... Hier sind die LootTables:
https://github.com/BakermanLP/ProjectRET-AoT/tree/1.11.2/dumps/loot_tables/immersiveengineering/chests

Theoretisch sollte das über den LootTweaker funktionieren, aber das hatte bisher noch keiner getestet. Ich weiß nicht, ob sich der Aufwand für die Nuggets echt lohnt.

**Comment by TheSnowyChickens** [comment]
Wenn fügt ein shapeless rezept ein, das einfach immersive Nuggets in Thermal nuggets umwandelt/umcraftet. Ist ja quasi nur 1ne Zeile Code pro Nugget art

**Comment by DerOliDE** [comment]
Loot Table bereinigt, bereits gelootetes weiterhin nicht kompatible.

**Comment by TheSnowyChickens** [comment]
Sehr gut, danke Oli.
