### ISSUE TITLE
Vermutlich weitere crashes aufgrund der Mail Mod.

### ISSUE THREAD

**Issue by niclaszockt** [BakermanLP/ProjectRET-AoT#231]
Als ich am 07.03.18 um ca. 16:45 auf die Mailbox geklickt habe ist der Server Süd abgestürzt.
Anbei meine kompletten Log Datei des Tages.

Sollte es noch Fragen geben bin ich im Discord unter dem Namen Niclaszockt zu erreichen.

[fml-junk-earlystartup.log](https://github.com/BakermanLP/ProjectRET-AoT/files/1790035/fml-junk-earlystartup.log)
[fml-client-latest.log](https://github.com/BakermanLP/ProjectRET-AoT/files/1790036/fml-client-latest.log)
[CustomNPCs-latest.log](https://github.com/BakermanLP/ProjectRET-AoT/files/1790037/CustomNPCs-latest.log)
[2018-03-07-0.log](https://github.com/BakermanLP/ProjectRET-AoT/files/1790040/2018-03-07-0.log)

[latest.log](https://github.com/BakermanLP/ProjectRET-AoT/files/1790033/latest.log)

**Comment by DerOliDE** [comment]
Ich hänge mich mal an den Thread dran, weil es auch mit der Mail Mod zutun hat.

Fehler im Log kA ob relevant oder nicht aber sie einfach mal an dieser Stelle erwähnt. :)
https://gist.github.com/DerOli82/8265d205f92f47a879d4381243fb777e

**Comment by lordjoda** [comment]
OK interessant. Der Fehler tritt auf wenn er eigentlich per reconnect eine neue Connection erstellt haben sollte...

**Comment by lordjoda** [comment]
Werde schauen dass ich das mal umschreibe -.-

**Comment by DerOliDE** [comment]
Scheint nicht mehr aufzutreten, wenn doch einfach Issue wieder öffnen. :)
