### ISSUE TITLE
Botania-Quest Bugged (Ein Zauberstab)

### ISSUE THREAD

**Issue by FluxBob** [BakermanLP/ProjectRET-AoT#232]
Die Quest lässt sich nicht abschließen. Es ist egal welche Farben man verwendet.

Auch das manuelle submitten bringt leider nix.

**Comment by hellamie** [comment]
ändern ist gemacht. mus nur noch auf allen servern hochgeladen werden

**Comment by DerOliDE** [comment]
Kümmer ich mich morgen drum.

**Comment by DerOliDE** [comment]
Beim nächsten Server Neustart sollte der Fix aktiv sein.
