### ISSUE TITLE
Manatablett Quest

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#234]
Issue posted by Lysandro: Also ich hab nun 4 Manatablett's aus 3 verschiendenen Craftingbenches (Tinkers, Minecraft, EZStorage) und 2 Craft-Varianten -> Kein Erfolg für die Quest :(

**Comment by hellamie** [comment]
änder ich bis Donnerstag ab

**Comment by Lysandro** [comment]
Merci
