### ISSUE TITLE
Modanfrage: Akashic Tome

### ISSUE THREAD

**Issue by Lysandro** [BakermanLP/ProjectRET-AoT#235]
Ich habe es noch nicht getestet, Frage aber trotzdem mal :)

DA es doch einige "Anleitungen" in Form von Büchern gibt. Wäre da ggf:
Akashic Tome
https://minecraft.curseforge.com/projects/akashic-tome

Sinnvoll?

**Comment by BakermanLP** [comment]
Leider funktionieren nicht alle Bücher in dem Mod. Vazkii hat leider auch eine extrem schlechte Art mit Updates um zu gehen. Das hatte ich bereits leidlich erfahren müssen mit dem Mod Quark. 
Die Idee ist gut, aber mir zu gefährlich jetzt damit zu experimentieren. Sorry
