### ISSUE TITLE
Iventar Bug: Item verloren und verdoppelt

### ISSUE THREAD

**Issue by Lysandro** [BakermanLP/ProjectRET-AoT#236]
Hi ich hatte eben einen Inventar Bug,
Um exakt 00:00 Ingamezeit hat sich mein Inventar verbugt bzw. items sind weg, dafür andere doppelt, Siehe screenshot.

Ich stand in der Mining Welt und wollte eigentlich die Pflanzen für Roots züchten.
Da beim Mondhöchststand nichts ging, warte ich auf 00:00 Ingamezeit, was nach Sonnenaufgang ist.
Auch keine Roots stahlen, weswegen ich dann wieder zurück wollte und ich das inventar gesehen habe.....
![2018-03-14_21 48 28](https://user-images.githubusercontent.com/5596977/37430381-47404dd8-27d2-11e8-894d-654c9a408e3f.png)

Die doppelten Items sind der Witch Hat, Book of Herblore, Portable Inventroy Remote Access.

Verschwunden 1 Rucksack mit Items und die Pfeile für den Bogen, weswegen ich es merkte :)

**Comment by DerOliDE** [comment]
Ich behaupte jetzt einfach mal, dass es mit dem Inv Sync zusammen hing und schließe das erstmal ab. Wenn es wieder auftauchen sollte, den Issue einfach wieder aufmachen. :)
