### ISSUE TITLE
[Automated Restone] Redstone Wire leitet kein Signal

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#237]
Redstone Wire leitet kein Singal mehr nachdem Chunk entladen/geladen wurde.

@CD4017BE weiß bescheid.

**Comment by DerOliDE** [comment]
@BakermanLP Wurde gefixt, muss nur noch geupdatet werden.

**Comment by CD4017BE** [comment]
Nein das ist ein Missverständnis, **dieser bug** wurde noch nicht gefixt. Die neue version die ich erwähnt hatte fixt nur einen Clients-seitigen Grafikbug mit Chisel-Blöcken als pipe covers.

**Comment by DerOliDE** [comment]
Okay dann hat das @Lysandro schon ungünstig im Discord ausgedrückt, er hatte nämlich von Redstone Steuerung und Mod update geredet. ;)

**Comment by CD4017BE** [comment]
ja er wollte seine redstone leitungen mit chisel blöcken covern und hat sich beschwert, dass die hässlich aussehen.

**Comment by Lysandro** [comment]
Ja, aber nicht das sie kein Signal leiten würden! Ich mach später einen neuen Issue auf. Ist ja wie bei mir in der Arbeit ;) ein Issue, mind. 2 Bugs/Fehler/CR im Inhalt ;)

**Comment by DerOliDE** [comment]
Ich hab nur Redstone Steuerung und Mod update gelesen und es hiermit assoziiert. ^^

**Comment by CD4017BE** [comment]
so jetzt gibt es aber auch hierfür einen fix:
- [CD4017BE_lib-5.3.2](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v5.3.2)
- [AutomatedRedstone-5.2.4](https://github.com/CD4017BE/AutomatedRedstone/releases/tag/v5.2.4)

**Comment by DerOliDE** [comment]
Das ging aber ...fix...

Okay okay 1€ in die schlechte Wortspielkasse. :D

**Comment by Lysandro** [comment]
ich spar mir dann den issue, mit der Version ist beides weg :P

**Comment by BakermanLP** [comment]
Kommt im nächsten Update mit rein, ich hatte heute nur Zeit um durch Curseforge zu blättern.
