### ISSUE TITLE
server kapput

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#238]
Issue posted by Snickers_LP: ich habe geschpielt und der server stützt ab dan ging er nicht mehr

**Comment by DerOliDE** [comment]
Leider als Bug Report nicht hilfreich, ich vermute dass es teile der Mail Mod Problematik ist

Cross-Ref: https://github.com/BakermanLP/ProjectRET-AoT/issues/231
