### ISSUE TITLE
RP Bug: Vertikaler Bereich

### ISSUE THREAD

**Issue by Lysandro** [BakermanLP/ProjectRET-AoT#239]
Hi,
der Vertikale Bereich von RP stimmt nicht, der ist aktuell bei 0-0, sollte aber von 0-255 sein....

![2018-04-03_22 30 23](https://user-images.githubusercontent.com/5596977/38275116-2158f0c4-3791-11e8-8bce-636fce95c92f.png)
![2018-04-03_22 45 41](https://user-images.githubusercontent.com/5596977/38275117-217bd3dc-3791-11e8-909b-72e264607911.png)

**Comment by Lysandro** [comment]
und einen Workaround gefunden
/rp expand-vert [regionName]

/Edit DerOli82, copy n' past aus Discord
Ja ist bei einem Gebiet aufgetreten das ich released und neu geclaimed hatte. Ging ja auch nicht mit /rp pos1 und /rp pos2, sofern du dich erinnerst. Zaun ziehen hat geklappt. Ich teste es später wenn ich die Zeit finde mit einem anderen Minecraft Account....

**Comment by DerOliDE** [comment]
In einem neuen Gebiet oder Deinem vorhandenen? Gab beim Update ein kleines Problem damit, dass RP sein Config Verzeichnis von RedProtect in redprotect umbenannt hat, eventuell ist beim Daten kopieren etwas schief gelaufen. Ich hab @BakermanLP noch gesagt, ich traue Minecraft nicht, wenn man so etwas on the fly ohne Server stop macht. :D

**Comment by DerOliDE** [comment]
Problem gefunden und gelöst. In der neuen Version gibt es in der Config ein:
```
claim {
    maxy=-1
    miny=-1
}
```
Das fehlt im alten Config File und er setzte es dann automatisch auf 0. 
@BakermanLP Werde das gleich auf alle Server und ins Template Verzeichnis kopieren.
