### ISSUE TITLE
Kapitel 3 - Portierung von 1.11.2 auf 1.12.2

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#240]
**Known Problems:**
- Alle Kabel aus Thermal Dynamics und Immersive Engineering verschwinden bei der Portierung.
- Ein paar Essenzen aus Mystical Agriculture verschwinden.

**Portierung eigener Mods**
- - ~~~[ ] Random Restockable Crates ( **Help Wanted**, eventuell mit Baker absprechen. )~~~
- - ~~~[ ] Mail Mod ( **Help Wanted**, eventuell mit Jojo absprechen. )~~~
- - [ ] Modpack Utils ( Wird von mir erledigt. )

**Tests**
- Achivement Books für 1.12.2 kompilieren und testen https://github.com/meza/achievementbooks/tree/1.12 ( **Help Wanted** )
- Immersive Railroading auf 1.12.2 testen
- Base Metals als Hardcore Ore Alternative testen

PS: Testserver/-version gibt es im laufe der Woche.

**Comment by BakermanLP** [comment]
Können wir den eigentlich schliessen?

**Comment by DerOliDE** [comment]
Ja ich mach das mal dicht.
