### ISSUE TITLE
Bug - Iron Door

### ISSUE THREAD

**Issue by Lutze53** [BakermanLP/ProjectRET-AoT#241]
Die Iron Door lässt sich nur platzieren, aber nicht öffen.

**Comment by hellamie** [comment]
meine geht mit Knopf einwandfrei

**Comment by DerOliDE** [comment]
Iron Doors brauchen ein Redstone Signal damit sie sich öffnen. Falls das fehlende Signal nicht der Fehler ist, mal schauen ob von irgendein umliegenden Block irgendwelche Signale gesendet werden, welche die Tür dauer offen halten.

**Comment by Lutze53** [comment]
achso ok dachte die kann man so öffen, na dann ist ja alles OK :)
