### ISSUE TITLE
[Mod Request] Signedit

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#242]
https://minecraft.curseforge.com/projects/signedit

Kleine komfort Mod, die einem ermöglicht Signs zu editieren, ohne sie abreißen zu müssen.

**Comment by Lutze53** [comment]
Klingt sehr gut :)

**Comment by TheSnowyChickens** [comment]
Wusste garnet, das es das Feature auch allein stehend gibt, kannte es nur von "Quark". :)

**Comment by BakermanLP** [comment]
So, ist nun mit drinnen in der 1.12.2er Version
