### ISSUE TITLE
Benutzte Chisel verschwinden aus dem Inventar bei Neustart

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#243]
Issue posted by Tr4pp3r: Wenn ich das Spiel beende und neu starte verschwindet mein chisel von c&b aus dem Inventar. ich habe das bisher nur bei chisel beobachtet, die auch verwendet wurden.

**Comment by Lutze53** [comment]
Das ist aber nur, wenn die Chisel im Charakter-Inv sind. In einem Beutel bleiben sie erhalten.

**Comment by hellamie** [comment]
unbekannter Bug..habe ich auch bei jedem server Wechsel oder neustart ist der Weg. Einfach im Rucksack haben. Oder genug Dias auf vorrat haben

**Comment by DerOliDE** [comment]
In 1.12.2 gefixt :)
