### ISSUE TITLE
Serverprobleme

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#244]
Issue posted by Reap_Hawk: Hallo^^, ich wollte mal mit eurem Modpack anfangen und auf dem Online Server spielen. Leider sagt der mir Connection Lost; Disconnected. Kann mir da jemand weiterhelfen, oder ist der Server nicht mehr aktiv?

**Comment by CD4017BE** [comment]
Nein das problem hatte ich gestern nach einem Serverneustart auch, woran es liegt weiß ich aber nicht. Aber davor hatten wir durchschnittlich ca. 77% uptime, also dass gelegentlich einen halben tag einige der server down sind kann durchaus vorkommen.

**Comment by DerOliDE** [comment]
Im Moment ist der komplette Server down, ich komme nicht mal mehr auf die Konsole. -.- Natürlich muss so etwas passieren, wenn Baker gerade in Urlaub gefahren ist....

**Comment by CD4017BE** [comment]
Ach Oli was hällst du eigentlich davon, die server über eine Art launcher auszuführen, der sich dann z.B. auch um automatische tägliche Neustarts, sowie Neustarts nach crashes kümmert?
Könnte man vielleicht zum nächsten Age einführen. Wenn man ganz fancy ist lässt man den auch gleich automatisch crash-reports auf github posten (deine modpack utils mod kann sowas ja bereits).

**Comment by DerOliDE** [comment]
Die Minecraft Instanzen starten täglich automatisch neu, irgendwann zwischen 3-4 Uhr und ein Neustart nach einem Crash wäre mit Linux Boardmitteln auch möglich dafür gibts pros und cons, so etwas automatisch laufen zu lassen.

Das aktuelle Problem lässt sich damit auch nicht bewältigen, da der Server, nicht nur die Minecraft Instanzen, auf überhaupt nichts mehr reagiert und ich auch nicht via SSH drauf komme.

Crash Report automatisch uploaden mag praktisch klingen, aber spätestens wenn wegen einem bekannten, aber noch nicht gefixten, Problem immer und immer wieder der selbe Crash-Report automatisch hochgeladen wird, wird es lästig und imho mehr arbeit als diese manuell zu durchwühlen.

**Comment by CD4017BE** [comment]
Ich hatte mir zum auto upload von crash reports schon einige gedanken gemacht und mir überlegt die anhand der 1. Zeile im exception stacktrace zu identifizieren: Gleiche exception in der gleichen Zeile der gleichen Methode = wahrscheinlich gleiche Ursache.
Sprich der extrahiert mit regex die entsprechende Zeile prüft ob die schon in einer entsprechend angelegten liste steht (text Datei), wenn nicht wird der hochgeladen und die Zeile zur liste hinzugefügt, sonst ignoriert.
Da die server getrennt laufen könnte zwar immer noch im worst case der selbe crash von jedem der server einmal hochgeladen werden.

Den Hauptnutzen den ich in den crashreport uploads sehe, ist, dass zum einen nicht ein Großteil untergeht und nie beachtung geschenkt wird. Und zum anderen die developer sich gleich Gedanken machen und debuggen können und nicht erst darauf warten müssen, dass zuständige Personen zeit haben und die zuschicken.

**Comment by BakermanLP** [comment]
Server ist gerade neu gestartet worden per Hardware Reset

CD4017BE <notifications@github.com> schrieb am Mo., 21. Mai 2018, 15:41:

**Comment by DerOliDE** [comment]
@BakermanLP Danke, alle Instanzen laufen wieder.

@CD4017BE Ich schaue mir, früher oder später die Crash-Reports an, z.Z. schmiert das Ding aber fast ausschließlich ohne Crash-Report ab und auch im Log steht nichts hilfreiches. Wenn irgendwas bzgl. Deiner Mod drin steht, hatte ich Dir das ja auch immer weitergeleitet wie zuletzt das hier: https://gist.github.com/DerOli82/1b74be0b2473bfd8e1310b829df7f528

Das ist z.Z. der einzige Fehler der bei Deiner Mod auftritt, weil es unsererseits noch kein Modpack Update gegeben hat.

Aus meiner Perspektive, ist nicht die Wahrnehmung der Reports das Problem, sondern die zur Verfügung stehende Zeit, um diese Auszuwerten, den Fehler nachvollziehen, zu reproduzieren und vor allem Wechselwirkungen zwischen unterschiedlichen Mods auszuschließen. Ein Crash-Report bringt dem Entwickler ja auch nichts, wenn der Fehler nicht nachvollziehbar ist. Ich kann Dir wenn Du Zeit und Lust hast, auch gerne einmal die Woche alle Crash-Reports schicken und Du übernimmst den Job.

**Comment by DerOliDE** [comment]
Ich schließ das hier mal ab, da das damalige Problem beseitigt ist.
