### ISSUE TITLE
der buck report buton ist im weg

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#245]
Issue posted by XCO_Yoshi: er wired auf einem gie scal von normal mitenn auf dem scren über dem options buton

**Comment by DerOliDE** [comment]
Der Fehler ist bekannt und gefixt, wird aber nicht mehr vor Kapitel 3 bzw. den Update auf die 1.12er Version im Modpack geupdatet werden.

**Comment by DerOliDE** [comment]
Gefixt in der 1.12.2er Version daher schließe ich das hier mal ab.
