### ISSUE TITLE
[1.12.2] Probleme beim Einloggen -> Vermutung Furnus

### ISSUE THREAD

**Issue by Lysandro** [BakermanLP/ProjectRET-AoT#255]
Log hängt an
Folgendes ist im Crachlog
https://gist.github.com/DerOli82/6342775ca289ae95c108e97417b62815

[latest.log](https://github.com/BakermanLP/ProjectRET-AoT/files/2112746/latest.log)

**Comment by DerOliDE** [comment]
Ich war mal so frei den wall of text auszulagern. :)

**Comment by Lysandro** [comment]
So mit anderem Rechner getestet -> Selber fehler
Mit 2. Account getestet -> Sobald man in "Renderrange" kommt selber Fehler
Logs hängen an.
[latest.log](https://github.com/BakermanLP/ProjectRET-AoT/files/2116998/latest.log)
[crash-2018-06-19_23.28.10-client.txt](https://github.com/BakermanLP/ProjectRET-AoT/files/2117003/crash-2018-06-19_23.28.10-client.txt)

**Comment by BakermanLP** [comment]
Wir könnten den Block löschen (wenn wir nicht in der Nähe sind), da die genauen Koordinaten im Log angegeben sind.
``` Block location: World: (242,78,-491) ```

**Comment by Lysandro** [comment]
Denke das ist die beste Lösung :) 👍

**Comment by DerOliDE** [comment]
Hab den Block an genannter Position in Luft aufgelöst.

**Comment by DerOliDE** [comment]
Auf North und South ist die Mod z.Z. disabled bleibt die Frage, ob wir Furnus nicht komplett rauswerfen, aber den Issue mache ich vorerst dicht.
