### ISSUE TITLE
[1.12.2] Inhalt eines "crashes" beim Server wechsel

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#257]
Ich öffne einfach mal hier ein Post, damit ich es übersichtlicher machen kann, als im Discord Chat. ^^

Erstmal etwas zusätzliches für das bekannte problem beim Serverwechsel bezüglich des Inventares, vllt. ist es hilfreich.
https://paste.dimdev.org/esehazahir.mccrash

hier nochma ein zweiter, ka. ob da was anderes is:
https://paste.dimdev.org/ixaxefolak.mccrash

+beim einloggen hatte ich heute einen perma spam vom *wahrscheinlich* inv. sync Mod, der mit beim wechsel des Feldes in der Hotbar immerwieder die "Please wait a while ... inventory sync" ausspuckte.

**Comment by BakermanLP** [comment]
Da ist leider in beiden Crash Reports nicht wirklich eine für uns relevante Information enthalten.

**Comment by TheSnowyChickens** [comment]
Schade.
