### ISSUE TITLE
"Ae" cracht das Spiel sobald ich es aufmache

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#258]
https://gist.github.com/DerOli82/a9dc83f129318560b61eaf347219c2db

**Comment by BakermanLP** [comment]
Laut dem Crash Report ist der Mod Furnus an dem Crash beteiligt oder Schuld. Lasst uns alle Furnus Dinge entfernen und dann weiter sehen.

**Comment by hellamie** [comment]
die Funsucce die Rumstehen?..die im Ae komm ich ja nicht ran um rauszumachen..den rest kann ich gleich mal in ne kiste packen

**Comment by hellamie** [comment]
aus ge cracht danke
