### ISSUE TITLE
tinkers construct macht Blödsinn 

### ISSUE THREAD

**Issue by XCOAnnika** [BakermanLP/ProjectRET-AoT#260]
Mann kann keine Signalum bowlimb mehr machen

**Comment by TheSnowyChickens** [comment]
Hab etwas dazu noch:
- Enderium tool rod lässt sich nicht gießen
- Platinum Large Plate lässt sich nicht gießen

**Comment by DerOliDE** [comment]
Wird genau so wie das hier https://github.com/BakermanLP/ProjectRET-AoT/issues/254 mit dem darunter verlinkten Problem zusammen hängen.

**Comment by hellamie** [comment]
Es lässt sich serh wenig gießen. Nur Eisen Werkzeuge. Sonst fast garnichts....Wähh heul flennn

**Comment by BakermanLP** [comment]
UniDict will da gerade nicht so, wie ich will. Eventuell wenn ich UniDict auf zuerst Thermelexpansion Material setze, könnte es gehen. Ich teste mal
