### ISSUE TITLE
[1.12.2] Der Chat ist seltsamm

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#261]
Bei mir hab ich folgendende probleme:
- Ich kann kein "J" ein tippen
- wenn ich "gehen" ein tippe und es absende, kommt "Gehen" dabei raus.
- ebenso ist ":D" -> ":d"
- ein komplett Server übergreifender Channel wäre net schlecht.

**Comment by CD4017BE** [comment]
Es besteht die Vermutung, dass der Chat eine serverseitige Rechtschreibautokorrektur besitzt, die auf Englisch eingestellt ist.

**Comment by BakermanLP** [comment]
Schau dir mal den Mod ChatTweaks an, der ist nämlich im Modpack installiert:
https://minecraft.curseforge.com/projects/chat-tweaks
Vielleicht habe ich da was verkonfiguriert.

**Comment by TheSnowyChickens** [comment]
Ich kann in den Configs nix insachen "Rechtschreib korrektur" oder "Spracheneinstellung" finden. Auch bekomme ich dieses Fenster (wie auf Curse gezeigt) nicht geöffnet, die Taste für Chat Tweaks ist nicht doppelt belegt und auch eine umbelegung hilft nicht. (Getestet auf dem Server auf South)

Vllt. wird das über die buttons im chat selbst geöffnet, das schaue ich nochma nach. :)

Ehmm ne, ich hab da kein Options Button, also ka. somit.

**Comment by hellamie** [comment]
geht fürs erste mal richtig
