### ISSUE TITLE
[1.12.2] PlusTIC fehlt

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#264]
Hallo,

in 1.11.2 war "PlusTIC" mit im Pack und dies ist nun nicht mehr aktuell drinne, ka. ob wegen eines Fehlerfalles oder einfachem vergessen.
Hiermit frage ich nun, ob es demnächst vllt. wieder mit ins Pack kommen kann, denn der verlusst dieses moddes, lässt viele Werkzeuge mit leeren Komponenten entstehen.
-> https://minecraft.curseforge.com/projects/plustic

Danke

**Comment by BakermanLP** [comment]
Der Mod musste leider raus fliegen aus dem Modpack, da er in der 1.12.2er Version ziemliche Probleme bereitet hatte. Sorry!

**Comment by TheSnowyChickens** [comment]
Ist es möglich, wenn er noch ein paar bug fix updates bekommt, das ihr es dann nochma versucht?

Oder die alternative "Moar Tinkers" vllt. mal in betracht ziehen? https://minecraft.curseforge.com/projects/moar-tinkers
