### ISSUE TITLE
[1.12.2] Immersive Hämmer duplication bug

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#265]
Hi,

wenn man 2 verletzte Immersive Hämmer im 2x2 Inventar crafting zu einem mehr heilen zusammen craften will, kann man quasi unendlich volle dabei heraus bekommen.

![2018-06-21_16 55 57](https://user-images.githubusercontent.com/29357962/41727207-15048eb6-7574-11e8-9c86-08502f47459d.png)

**Comment by DerOliDE** [comment]
Schein schon gefixt zu sein, aber eventuell noch nicht released.
Cross-Ref: https://github.com/BluSunrize/ImmersiveEngineering/issues/2990

**Comment by TheSnowyChickens** [comment]
Soeben ist ein Immersive Update raus gekommen, worin dieser Bug gefixed seien sollte.
https://minecraft.curseforge.com/projects/immersive-engineering/files/2580816

**Comment by BakermanLP** [comment]
Das sollte nun mit dem aktuellen Release https://github.com/BakermanLP/ProjectRET-AoT/releases/tag/v1.1.1 erledigt sein. Bitte verifizieren und schliessen.

**Comment by TheSnowyChickens** [comment]
Es tritt nicht mehr auf, in meinem Test.

*Close now*
