### ISSUE TITLE
[1.12.2] Das Mob verhalten spinnt etwas rum

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#268]
Hallo,

mir ist aufgefallen, im vergleich zu 1.11.2, das die mobs (Skelette und Creeper) recht seltsamm geworden sind. 
Skelett sachen:
- Sie schießen schon von einer weit entfernten entfernung, ohne das ein direkter blick kontakt besteht.
- Bsp.1: Bei mir in der Base ballern sie die große Glas Front zu, ohne das ich auch in der nähe war und meine Türen waren zu.
- Bsp.2: In der Mining Welt habe ich nach unten gegraben, zu einer Höhle, und schon als ich langsam in die nähe kam, ballerten die Skelette los (es waren massive Steine über mehrere Blöcke entfernung, dazwischen)

Creeper sachen:
- Bsp.1: Creeper explodieren hinter geschlossenen Eisentüren einfach so, wenn man in der nähe steht (getestet an den Eisentüren in den End dungeons)
- Bsp2: Einfach random

Ich weiß nicht, ob ihr das vielleicht extra so geändert habt für die 1.12.2, oder ob das teils nicht gewollt ist.
Ich wollt das nur mal so protokollieren.

Thx

**Comment by hellamie** [comment]
Ich werde gerne von ihnen Ignoriert...bin im Spawner und die schauen mich nur blöde an..nein ich WAR NICHT mehr im Creativ.

**Comment by TheSnowyChickens** [comment]
Ich habe hier noch ein beispiel, das da irgendwas nicht ganz ok ist:
![2018-06-27_03 21 45](https://user-images.githubusercontent.com/29357962/41947683-501af294-79b9-11e8-9321-56947791d5f6.png)

Wie im Bild zusehen (vllt. etwas klein, sry), sind dort extrem viel mobs verklumpt auf einem haufen, diese waren zuvor verteilt in dem cave-system. Als ich näher kam, wurde es zum klumpen.

**Comment by BakermanLP** [comment]
Bitte das Mob Verhalten nochmal verifizieren, da ich hier einen Mod entfernt habe, der das verursachen könnte.

**Comment by hellamie** [comment]
Scheint wieder normal zu sein..gestern direkt in die Luft gesprengt worden

**Comment by BakermanLP** [comment]
Dann würde ich das mal schliessen.
