### ISSUE TITLE
[1.12.2, Crafting recipe request] FastHopper -> Hopper (Vanilla)

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#270]
Hallo,

ich hätte ne einfache Frage.
Ist es möglich das ihr ein Rezept einfügt, das einen FastHopper wieder zu einem normalen Hopper verwandeln lässt?
FastHopper können nämlich nicht für normale Hopper Rezepte verwendet werden, deswegen frage ich.

Thx

Beispiel Rezept (CraftTweaker) : recipes.addShapeless(<minecraft:hopper>, [<refinedrelocation:fast_hopper>]); 
(Die eckigen Pfeile, <>, werden hier von Github anscheinend automatisch weg gemacht, zumindestens oben im bsp. Rezept)

**Comment by hellamie** [comment]
Ich denke nicht..Da der Hopper so schnell und einfach gebaut ist sehe ich persönlich keinen Sinn in der zurückwandlung. An Mats sollte es bei dir echt nicht scheitern.

**Comment by TheSnowyChickens** [comment]
Ich hab halt gut 15 FastHopper im System rumliegen und kann die nicht gebrauchen :D
Deswegen frage ich.^^

**Comment by DerOliDE** [comment]
Also sorry, aber wegen 5 Iron und 8 Wood, ernsthaft? :P
Wenn Du die Fast Hopper nicht mehr brauchst, dann schmeiß sie halt weg, gibt eh viel zu viel Mats.
