### ISSUE TITLE
Umbau Github Repository

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#276]
Bitte im Moment keine Pushs / Commits oder ähnliches machen, ich baue gerade das Repository um.

Wenn dieser Issue geschlossen ist, könnt ihr wieder loslegen.

**Comment by BakermanLP** [comment]
Ich glaube, dass ich fertig bin mit dem Umbau. Jedes Kapitel bekommt seinen eigenen Branch, ist zwar nicht 100%ig optimal, aber wirkt hier übersichtlicher

**Comment by DerOliDE** [comment]
IMHO ist das sogar die bessere Lösung, da man nun leicht die unterschiede zwischen den Branches betrachten kann und somit die Config Änderungen pro Kapitel besser im Blick hat.

**Comment by BakermanLP** [comment]
So, ich denke ich bin mit dem Umbau fertig. Jedes zukünftige Kapitel bekommt seinen eigenen Branch
