### ISSUE TITLE
[1.12.2] Lava ist kaputt

### ISSUE THREAD

**Issue by TheSnowyChickens** [BakermanLP/ProjectRET-AoT#284]
Hi,
kurz beschreibung: https://bugs.mojang.com/browse/MC-9544

Lang beschreibung: Hat sich eine Lava quelle massiv ausgebreitet und man macht den source block weg, dann gehts einfach nicht weg. Säulen und kleinigkeiten verschwinden, aber kleinere bereiche bleiben.
Auch sollte sowas, wie im Bild, nicht gehen.

![2018-07-17_18 52 31](https://user-images.githubusercontent.com/29357962/42833083-757aaf4e-89f3-11e8-9ebe-a4aeb9ef1c8f.png)

**Comment by CD4017BE** [comment]
Möglicherweise kommt der server nicht dazu seine Blockupdate queues abzuarbeiten (wegen lag) oder irgendein prozess löscht diese ständig.

Zur Not benutz einfach einen Fluid Intake um die Flüssigkeiten zu entfernen, im `no block updates` modus entfernt der auch nicht-source-blöcke. (übrigens: Nein, die Maschine ist nicht für den Bug verantwortlich.)

**Comment by TheSnowyChickens** [comment]
Is möglich, jedoch warum geht Wasser ohne probleme weg? (Lava ist ja nur langsammer und breitet sich auf 4 auf)

**Comment by CD4017BE** [comment]
Lava ist wahrscheinlich aufgrund der langsameren Block Tickrate anfälliger auf Ticks die ausfallen oder zu falschen Zeitpunkt ausgeführt werden. Ich hatte auch schon mehrfach in Minecraft (modded, sowie unmodded) Fälle, wo ich dem Lava Abfluss mit manuellen Block-Updates nachhelfen musste.

**Comment by TheSnowyChickens** [comment]
Muss mich korrigieren. :D 
(das ist auf "East")
![2018-07-19_21 30 41](https://user-images.githubusercontent.com/29357962/42965742-0eff33bc-8b9b-11e8-952e-332a97b27b27.png)

**Comment by hellamie** [comment]
Ist das Problem überlebens Notwendig?..Ich denke mit genügen Sand ist es "Ertagbar"

Daher schließe ich das und wir können es wieder aufmachen wenn die wichtigen ServerTÖTENDEN Probleme alle weg sind
