### ISSUE TITLE
Bessere Bäume wachsen durch alles

### ISSUE THREAD

**Issue by Jan-Ellmers** [BakermanLP/ProjectRET-AoT#33]
Mir ist aufgefallen das die neuen schöneren Bäume durch die NeoTech Fluid Interface Pipe und durch ganz normalen Minecraft Stein wachsen.

**Comment by BakermanLP** [comment]
Es gibt ein paar ältere Bäume (BO2) Format und ein paar Bäume im BO3 Format, die das leider nicht checken. Interessant wäre ein Screenshot des Baumes.

**Comment by Jan-Ellmers** [comment]
https://www.dropbox.com/s/v1wzowb0rwfv2l6/Baum%20Test.zip?dl=0

Das ist eine kleine Welt in der ich mal etwas getestet habe. Auf der großen Steinfläche stehen viele Bäume die alle durch Stein durchgewachsen sind.
