### ISSUE TITLE
Hellamie's Feenliste ... oder auch machs richtig

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#37]
- [x] Flint Hühnchen nicht craftbar
- [x] Tumbleweed machen Felder kaputt
- [x] Lucky Bocks später in Farmwelt oder als Rewards
- [x] Zu Dunkel mit Hardcore Darkness auf 2 stellen
- Koordinaten an Beta Tester
- Rundgang zur Questwelt

**Comment by BakermanLP** [comment]
Ich überlege hier noch, ob manche der Hühnchen anders craftbar gemacht werden sollen, also nicht kreuzbar, sondern z.B 8 Flint um ein Ei gelegt im Crafting Grid gibt ein Spawn Egg oder so. Ebenso die höheren Hühner könnten so schwieriger gemacht werden.

**Comment by hellamie** [comment]
So ich habe mal die Hühnchen Rezepte durchgesehen.

folgende Rezepte werden mir nicht angezeigt:
 Log Chicken
Nether Quarz Chicken
Smart Chicken
Flint Chicken (wichtig am Anfang)
Sand Chicken
chickenosto  (häää?)
Funwaychicken


Wo bei man ehe mal überlegen soll ob die Hühner nicht je nach "Time" freigeschaltet werden sollten.

**Comment by hellamie** [comment]
So

Fehler

1) wenn ich aus Animalia das Schweinefutter mache kann ich Eimer verdoppeln. 
2) Die Hünchen aus Hatchet spwanen nicht mehr. Animalia schaltet das wohl aus., keine anderen Tiere neben dem Mod.
3)

**Comment by hellamie** [comment]
1) Erfrieren ist Mist, und wenn man  nicht gerade erfriert dann stirbt man an Hitzschlag. Entweder besser Balancen oder raus..ahahahah

2) Das das ganze Gemüse über Nacht wegstirbt ist Totaler mist.

3) wenn Ich die richtigen Kühe melke bekomme ich Friesien Bucket of milk. Damit kann ich Käse machen. Aber dabei verschwindet der Eimer..Rezept muss überarbeitet werden.

**Comment by hellamie** [comment]
Ich spiele gerade kreativ mit Mods rum

1) Tinker Construckt Bombe ENLF RAUS..oder sooooo schwer das gut ist..aber ein Flint ein Gunpowerder halbe basis weg?  nööö

2)

**Comment by BakermanLP** [comment]
ToughAsNails ist im Moment raus, da man den nicht gut konfigurieren kann und ein paar Features fehlen. Damit sind Erfrieren, Gemüse über Nach weg usw weg. 
Zur Übersichtlichkeit für mich, habe ich aus den restlichen Punkten neue Issues gemacht.
- https://github.com/BakermanLP/ProjectRET-AoT/issues/56
- https://github.com/BakermanLP/ProjectRET-AoT/issues/59
- https://github.com/BakermanLP/ProjectRET-AoT/issues/60

... und diesen hier geschlossen
