### ISSUE TITLE
Slate Ore Generierung entfernen 

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#40]

**Comment by Grambosch** [comment]
Kurze Frage , Weshalb? Das ist ja für Decoblocks lediglich also wie Diorite und so

**Comment by BakermanLP** [comment]
Das müsste aus dem Mod raus und in Terrain Control rein. Ich möchte alle Welt Generierungen in Terrain Control drinnen haben. D.h. alle Erze, alle Pflanzen, alle Mobs usw. sollen durch Terrain Control erzeugt werden. Damit ist nur ein Mod für die Weltgenerierung verantwortlich. Ich erhoffe mir hiermit eine Performance Steigerung. Nebenbei ist es eine Erleichterung, da alles an einem Ort dann steht.

**Comment by Grambosch** [comment]
Ahso
