### ISSUE TITLE
Epic Siege Mod konfigurieren oder entfernen

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#42]
Mobs sind reichlich hart eingestellt im Moment

**Comment by XCOAnnika** [comment]
Entfernen Von mir und cd

**Comment by BakermanLP** [comment]
Die Einstellungen stellen nur am Anfang ein wirkliches Problem dar. Deswegen bleiben die Einstellungen erst mal so.
