### ISSUE TITLE
Server und Bungeecord Permissions einrichten

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#49]
- Spieler sollen den Server wechseln können
- Eventuell weitere Befehle für Spieler freischalten

Hängt zusammen mit Ref #46

**Comment by BakermanLP** [comment]
Zwei Server Mods müssen noch drauf:
- Permission(Irgendwas)
- Gebietsschutz (TownyPlugin ...)

**Comment by BakermanLP** [comment]
Hier eine erste Liste von Protection Mods:
- https://forums.spongepowered.org/t/shield-anti-grief-with-flag-gui-redprotect-1-8-9-1-11/11846
- https://forums.spongepowered.org/t/bomb-universeguard-a-worldguard-solution-for-sponge/17455
- https://forums.spongepowered.org/t/api-5-x-6-x-foxguard-the-flexible-world-protection-solution/9952
- https://forums.spongepowered.org/t/earth-africa-nations-v2-4-towny-like-protection-plugin/12127

**Comment by CD4017BE** [comment]
Hab mir die links mal angesehen:
- **home sweet home** scheint nur zum setzen von "home" Teleport punkten zu sein und keine Gebiet protection zu beinhalten.
- **Foxguard** und **universegguard** scheinen nur rein Admin organisierte Plugins zu sein.
- **Africa Nations** ist Staats orientiert mit einzelnen Spielern die als Verwalter für groß gebiete fungieren und kleinere Abschnitte davon den anderen zuweisen mit verschiedenen Hierarchien. _Möchte man das?_
-  **RedProtect** erwähnt explizit, dass Spieler ihre Regionen selbst organisieren können und macht für mich auf den ersten Blick den kompetentesten Eindruck. Außerdem ist das das Plugin, wofür ich schon mal in mc-1.8 (die Mighty Pirates hatten da ja auch noch so ein server project) eine Brücke geschrieben hab, eventuell kann ich da den code wiederverwerten.

Ansonsten könnte man noch gucken was es für Forge Mods dafür gibt (die könnten möglicherweise mehr auf modded minecraft optimiert sein).

**Comment by BakermanLP** [comment]
Servermods sollten passen, weitere Vorschläge gerne, aber dann in einem neuen Issue.
