### ISSUE TITLE
Animalia das Schweinefutter mache kann ich Eimer verdoppeln

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#59]
Da bräuchte ich das Rezept, bei dem das passiert

**Comment by hellamie** [comment]
ein Eimer Milch mit 2 Gemüse oder 1 Gemüse und Brot ergibt ein Eimer Schweinefutter.  Bucket of Slope oder so

**Comment by BakermanLP** [comment]
Animalia ist neue Version drinnen, bitte auch hier testen.

**Comment by hellamie** [comment]
Eimer wird verbraucht. Alles richtig jetzt.
