### ISSUE TITLE
Friesien Bucket of milk zu Käse machen

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#60]
wenn Ich die richtigen Kühe melke bekomme ich Friesien Bucket of milk. Damit kann ich Käse machen. Aber dabei verschwindet der Eimer..Rezept muss überarbeitet werden.

**Comment by hellamie** [comment]
Eimer verschwindet immer noch beim Käse machen..

**Comment by BakermanLP** [comment]
Cross Ref: https://github.com/capnkirok/animania/issues/81
Da das Rezept aus dem Mod kommt, erst mal den Mod Autor angeschrieben. Ansonsten Custom Rezept mit Haltbarkeit Reduzierung des Holzrahmens.

**Comment by hellamie** [comment]
der Rahmen hat schon einen grünen Balken der weniger wird ;)

**Comment by BakermanLP** [comment]
Wurde durch den Mod Autor behoben.

**Comment by BakermanLP** [comment]
Close, da behoben durch Mod Update
