### ISSUE TITLE
Ich mag ein Netz (goldenlasso) Dings bums bitte

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#64]
Aus hatchery gibt es ein Netz mit dem lassen sich Tiere einfangen und im Inventar rumtragen. Ich finde es einfach, genial und mag so was haben.

**Comment by BakermanLP** [comment]
Leider bisher noch nichts gefunden

**Comment by Grambosch** [comment]
Ich meine in Tinkers wäre so was drin , gleich mal schauen

**Comment by BakermanLP** [comment]
Bitte im nächsten Beta Release die Stäbe aus Not Enough Wands testen:
- Capturing wand: capture any living mob (hostile or not) with a left click. Release it again with a right click

**Comment by BakermanLP** [comment]
Sollte jetzt alles passen.
