### ISSUE TITLE
Storage drawer spinnen.

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#68]
Ich weis nicht ob das nur bei mir so aussieht, aber die Dinger drehen sich optisch rum, oder zeigen nicht mehr an was drin ist. auch die Bewegung der Hand fehlt wenn ich was einräume...

Bitte jemand testen ob das nur an mir liegt.

**Comment by BakermanLP** [comment]
Kannst du das bitte mit der neuen Version nochmal testen, da ist eine neue Optifine Version nun drinnen. Eventuell kannst du, falls der Fehler noch besteht, einen Screenshot hier reinposten

**Comment by hellamie** [comment]
haben aufgehört
