### ISSUE TITLE
Optifine D7 und MalisisCore / Door crasht

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#70]
Crash log:
http://pastebin.com/trnU4V9S

Cross Ref:
https://github.com/Ordinastie/MalisisCore/issues/88

**Comment by BakermanLP** [comment]
Wechsel von Optifine D7 auf Optifine D6 und auf magische Weise ist der Fehler weg.

**Comment by Alheimerjung** [comment]
Ok danke, habe ich verbessert

2017-03-16 13:16 GMT+01:00 BakermanLP <notifications@github.com>:

**Comment by BakermanLP** [comment]
Fixed in MalisisCore 1.10.2-4.4.0.
