### ISSUE TITLE
[Mod Request] Inductive Automation & Automated Redstone

### ISSUE THREAD

**Issue by CD4017BE** [BakermanLP/ProjectRET-AoT#71]
Ich hätte gern meine mods mit im Pack und würde mich (wenn erwünscht) auch um deren Integration kümmern (konfigurieren, balancen, etc.).

### Einordnung:

**Automated Redstone** beinhaltet praktische Sensoren, Anzeigen, Breitband Signalkabel, sowie selbst designbare kompakte 1 Block redstone Schaltungen (Entwickelt mit der Absicht, möglichst Performance freundlich zu sein).
Zusammen mit TIS-3D und OpenComputers bildet das quasi die Evolution von simpler Roh-Hardware über Assembler zu high-level lua Programmierung. Ich würde sagen ElectricAge und ein par Features evtl. schon im SteamAge

**Inductive Automation** könnte man für ElectricAge ... ToTheStars einordnen, das würde ich dann via crafting rezepte splitten, dass es nach und nach freigeschaltet wird. Die Rezepte sollten am besten auch an den Schwierigkeitsgrad des Packs angepasst und mit anderen mods "verwoben" werden.

### Hinweise:

I.A. besitzt eine Maschine die bestimme Chunks vor Eingriffen anderer Spieler schützt (die ich deaktivieren würde weil sie nicht sonderlich Admin freundlich ist), dem entsprechend checken die anderen Maschinen (Miner, Builder, etc.) ob sie berechtigt sind bestimmte Operationen in bestimmten Chunks durchzuführen.
Das ganze ist auch extern als API zugänglich, dh. falls nötig kann ich eine Brücke zwischen dieser API und dem Plugin/Mod, welche ihr für Gebiet-Protection verwendet, schreiben, sodass die Maschinen nicht in unerlaubten Gebieten Blöcke platzieren oder abbauen können. (hab ich schon mal gemacht, war nicht sonderlich schwierig)

Alle crafting Rezepte aus meinen mods sind in einer config Datei definiert, die im Prinzip ähnlich wie ein MineTweaker-Script funktioniert (bloß andere Syntax).
Diese config bietet auch die Möglichkeit neue (einfache) Items zu erstellen. Das könnte womöglich nützlich beim Erstellen einiger crafting resource-queues sein.

**Comment by BakermanLP** [comment]
Wenn Automated Redstone nur "vereinfachte" Redstone Schaltungen anbietet, dann würde das entweder in "It's a kind of Magic" passen oder spätestens in "Steam Punk".

Inductive Automation hattest du schon richtig ins Electrical Age eingeordnet. 

Über ein Protection Plugin hatten wir gequatscht am Montag, und es wird definitiv eines geben. Welches haben wir aber noch nicht besprochen.

Den grundsätzlichen Schwierigkeitsgrad hatten wir bisher noch nicht auf dem Radar. Aber da finden sich garantiert passende Rezepte. 

Im Moment legen wir einige grundsätzliche Sachen fest. Wenn du Spaß daran hast, dann komm in unser Beta Tester Team. Tatkräftige Hilfe können wir immer brauchen.

**Comment by CD4017BE** [comment]
Ja da bin ich gern dabei, kannst mich eintragen.

**Comment by CD4017BE** [comment]
So zumindest meine [LibraryMod](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v5.0.0)und [AutomatedRedstone](https://github.com/CD4017BE/AutomatedRedstone/releases/tag/v5.0.0) sind jetzt fertig auf Minecraft 1.11.2 geportet und funktionieren premium. Inductive Automation 2 ist noch in Arbeit da ich es nicht nur porte sonder auch vieles komplett neu schreibe.

**Comment by BakermanLP** [comment]
Sind Beide gerade ins Modpack gekommen. Config für Automated Redstone würde ich sagen können wir lassen. Der Mod wird erst im zweiten Zeitalter mit dazu kommen. Dadurch erübrigt sich glaube ich zunächst mal eine spezielle Konfiguration.

**Comment by CD4017BE** [comment]
So mit [InductiveLogistics](https://github.com/CD4017BE/InductiveLogistics/releases/tag/v0.1.0) wäre schon mal die erste Fuhre an ehemaligen InductiveAutomation Features angekommen (hab Lord Jodas Rat befolgt, es in einzelne Mods zu splitten)

Die Rezepte können ruhig geändert werden, das sind erst mal nur Standartrezepte, die nur vanilla crafting Ingredienzen verwenden (ja der ultimate Tank kostet über 16 millionen glass panes).

Alle Rezeptänderungen in meinen mods möglichst über die jeweilige Config durchführen. Übrigens: das "shapedNBT"-Rezept könnte eventuell auch für andere Rezepte im Modpack nützlich sein, denn soweit ich weiß, hat CraftTweaker so etwas nicht [infos dazu hier](https://github.com/CD4017BE/CD4017BE_lib/tree/master-1.11.2/doc/recipeScript)

**Comment by CD4017BE** [comment]
Es gibt updates:
[CD4017BE_lib-5.1.0](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v5.1.0)
[InductiveLogistics-0.2.1](https://github.com/CD4017BE/InductiveLogistics/releases/tag/v0.2.1)
[AutomatedRedstone-5.1.0](https://github.com/CD4017BE/AutomatedRedstone/releases/tag/v5.1.0)

**Comment by DerOliDE** [comment]
In der https://github.com/BakermanLP/ProjectRET-AoT/blob/1.11.2/README.md ist noch ein "(Einschränkungen?)" vermerkt, darüber könnte man nochmal reden.

**Comment by CD4017BE** [comment]
Das ist glaube ich veraltet und bezog sich eher auf eine andere Mod die nicht ins Pack gekommen ist weil ich sie nicht auf 1.11 geportet hab. Die wurde nämlich in 1.11 durch eine abgespeckte nachfolgerversion ersetzt.

Aber falls ihr aktuell noch bei bestimmten Features Einwände haben solltet können wir das natürlich besprechen.

**Comment by DerOliDE** [comment]
Kapital 2 läuft, die Mods sind integriert, damit kann man das hier imho auch mal abschließen. :)
