### ISSUE TITLE
Kisten Mods - kann / soll einer raus?

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#72]
Wir haben aktuell folgende "Kisten" Mods drinnen:

- compactstorage
- ezstorage
- ironchest
- MultiStorage
- StorageDrawers

Ist da einer zu viel dabei? Ich habe da compactstorage ein wenig auf der Kickliste

**Comment by Grambosch** [comment]
Muss ich mich mal mit auseinandersetzen , ich schau mal rein heute mittag

**Comment by Grambosch** [comment]
Compact Storage bietet nicht viel zusätzlich zu anderen Mods der sollte problemlos raus können

**Comment by BakermanLP** [comment]
Gelöscht in 0.6er Version
