### ISSUE TITLE
Base Metal Hammer und OreExcavation

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#74]
Die Hammer aus Base Metal funktionieren nicht 100%ig mit OreExcavation

Cross Ref: https://github.com/Funwayguy/OreExcavation/issues/6

**Comment by BakermanLP** [comment]
Cross Ref: https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/117

**Comment by BakermanLP** [comment]
Sollte mit rechtsklick genauso funktionieren. Testen!

**Comment by Kappi85** [comment]
Die rechtsklick funktion der Hämmer aus ModernMetalls, BaseMetalls und BaseGems funktioniert.
Beim klopfen mit Vine Miner bauen alle Hämmer gleich ab, 3x3x2.
getestet im Survival mit Cobblestone, Gravel und Sand

Die Ore´s kann man auch per Rechtsklick zerkleinern.

**Comment by BakermanLP** [comment]
Laut Definition des Mod Autors ist das so gewollt. Also schliessen wir das einfach mal.
