### ISSUE TITLE
Client und anscheinend ServerCrash

### ISSUE THREAD

**Issue by Grambosch** [BakermanLP/ProjectRET-AoT#76]
Beim Versuch Better Questing nen Meeting Task mit nem CustomNPC zu geben:
http://pastebin.com/JcRk08TB

**Comment by BakermanLP** [comment]
Versuche es bitte nochmal mit der neuen Version, von CustomNPCs ist eine neue Version drinnen.

**Comment by Grambosch** [comment]
Hab mich der Huette samt NPC genähert und bei der Annäherung hats den Server zerissen. Ich nehm an der bestehende NPC ist kaputt. Crash Report meinerseits gibts leider nicht

**Comment by DerOli82** [comment]
Server Crash Report: http://pastebin.com/ZixWnTPD

**Comment by Grambosch** [comment]
http://pastebin.com/sEf1mNxP

**Comment by Grambosch** [comment]
Scheint ja erstmal weniger ein Problem von Custom NPC als mehr von BQ

**Comment by BakermanLP** [comment]
Sollen wir es weiterleiten als Issue?

**Comment by Grambosch** [comment]
Danke sehr
Dann arbeite ich vorerst mal an normalen Questen weiter.

**Comment by BakermanLP** [comment]
Der Mod ist im Moment für 1.11.2 nicht verfügbar, deswegen CLOSE
