### ISSUE TITLE
Voreingestellte Tastenbelegung nicht mehr da

### ISSUE THREAD

**Issue by Sharkuns** [BakermanLP/ProjectRET-AoT#81]
Seit Modpakupdate sind die Voreingestellten Tastenbelegungen nicht mehr da.
Nur noch die Standard Belegungen sind vorhanden.

**Comment by BakermanLP** [comment]
Bei einem Modpack Update auf dem Client fasse ich die Tastaturbelegung nicht mehr an. Wenn jemand was eingestellt hat, möchte er das ja nach dem Update auch so haben. Die Tastaturbelegung wird nur bei der ersten Installation und bei einer Neuinstallation neu geschrieben. 

Was hat sich den geändert?

**Comment by Sharkuns** [comment]
Ich meinte die Einstellungen die du reingemacht hast. Ich hatte da nix mehr geändert.

Was mir direkt aufgefallen ist das LightLevel war nicht mehr belegt und sieht nun auch anders aus. Es sind nur noch die Zahlen zu sehen und da muss man ab und an genau hinsehen.
![2017-03-22_14 24 23](https://cloud.githubusercontent.com/assets/26391981/24199806/510f7ee6-0f0b-11e7-8fe7-b1ddeff4abeb.png)

**Comment by BakermanLP** [comment]
Default Tastatur Belegung ändern:

Light Level Overlay wieder auf die F7
Misc -> Open Keyboard Wizard auf F6

**Comment by BakermanLP** [comment]
Sollte jetzt gefixed sein. Da waren zu viele Mods, die den Overlay darstellen wollten
