### ISSUE TITLE
Animania Tiere erzeugen keinen Dung

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#82]
Cross Ref: https://github.com/BeetoGuy/BetterWithMods/issues/278

Kann das jemand bestätigen oder dementieren?

**Comment by Sharkuns** [comment]
Werde da mal schauen wie es bei mir ist

**Comment by BakermanLP** [comment]
Ich hatte im kompletten Mod keinen Dung gefunden. Das war wahrscheinlich der Dünger aus dem Chickens Mod.

**Comment by hellamie** [comment]
die machen kenen "scheiß"

**Comment by lordjoda** [comment]
Grad mal in die Klassen geschaut. Die Animania Tiere erben von EntityAnimal was in BetterWithMods die einzige Voraussetzung ist siehe: https://github.com/BeetoGuy/BetterWithMods/blob/master/src/main/java/betterwithmods/event/MobDropEvent.java#L80
Daher sollte das eigentlich gehen. Habs aber im Spiel nicht getestet ob da noch Einschränkungen sind.
