### ISSUE TITLE
Splash Potion noch nutzbar !

### ISSUE THREAD

**Issue by Sharkuns** [BakermanLP/ProjectRET-AoT#84]
Ich vermute mal das die trinkbaren Potions im Stone Zeitalter raus genommen wurden, es wurden aber die wegwerfbaren Potions nicht rausgenommen ! ?

Die Angezeigten Effecte der Splash Potions gehen auch nicht weg, sie werden immer wieder erneuert, erst nach einem Relog sind sie weg, dies kann aber auch an Client Problem sein, müssten man mal austesten !

**Comment by BakermanLP** [comment]
Eigentlich sollte das "Stone Age" sich wie Vanilla anfühlen. Da gehören aber die Potions mit dazu. Theoretisch gebe ich dir Recht, dass das dann in die Magie Ecke geht. Aber dann müssten wir Redstone auch deaktivieren... Das würde mir zu weit gehen.

**Comment by Sharkuns** [comment]
ok, dachte die wären abgeschaltet worden weil sie nicht gingen. Wäre Super wenn 1 oder 2 da auch mal schauen obs bei ihnen geht oder ob da wo nen Bug ist. Ich schau heute Abend auch nochmal!

**Comment by BakermanLP** [comment]
Lassen wir sie an, damit sich das Stone Age nach "Besserem Vanila Minecraft" anfühlt.
