### ISSUE TITLE
Not Enough Wands Stäbe testen und eventuell Teile ausschalten

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#91]
Für die Bauer und für das Fangen von Tieren ist im nächsten Beta Release der Mod Not Enough Wands enthalten. 

Die Stäbe müssen alle getestet werden und nicht passende abgeschaltet werden.

**Comment by XCOAnnika** [comment]
ich könnte das morgen tuen

**Comment by hellamie** [comment]
Falls Oli noch nichts wo anders geschrieben hat.

Teleporting Stab: Portet dich ein paar Blöcke weit nach vorne.
Baustäbe 2 Stück (nicht näher beschrieben)
Capturing Stab: Fängt ein Monster oder Tier ein (teuer beim bauen)
Illumination Stab: Setzt ein Licht bubbel 
Displacement Stab: schiebt eine "Wand" 3+3 vorwärts
Moving Wand: Hebt 1 Block auf und setzt ihn wo anders wieder hin..( nur mit gras getestet)
Acceleration Stab. Erhöt die Ticks auf ein Feld/Block...RAUS
Protection Wand 1/2 Schützt eine Zohne vor abbau..(GM Onlie oder so )
Freezing Stab: versetzt eine Creatur in starre (ist ehe kaputt oder ich der benutzung zu blöd)
Potion Stab: Schleudert ein Zaubertrank (verbaucht statt 1 Trank erfahrung, so kann 1  Trank mehrfach auf ein was auch immer angewand werden)

**Comment by BakermanLP** [comment]
Wir hatten da am Montag etwas getestet und haben folgendes gemacht:
https://github.com/BakermanLP/ProjectRET-AoT/commit/d1931ddc3e029c9dde0b26d77652a5ba0a3fdbc1
- Ausschalten Protection und Master Protection Wand
- Ausschalten Acceleration Wand

**Comment by BakermanLP** [comment]
In Release 0.8.3 erledigt
