### ISSUE TITLE
Earth Life Mod nicht wieder findbar

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#92]
Ich bin gerade sehr verwundert, alle Spuren zum Earth Life Mod vom Author Betkekk sind verschwunden. 

Sollen wir so einen Mod drinnen lassen?

**Comment by Grambosch** [comment]
Dubios. Eher nicht schon allein wegen Supportgruenden

**Comment by BakermanLP** [comment]
Entfernt und damit close
