### ISSUE TITLE
Agricraft und Mystical Agricraft ?

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#94]
Dann stelle ich hier gleich zur Diskussion:
* [AgriCraft](https://minecraft.curseforge.com/projects/agricraft)
* [Mystical Agricraft](https://minecraft.curseforge.com/projects/mystical-agricraft)

**Comment by lordjoda** [comment]
Finde ich Ansich gut. Ich würde nur vorschlagen, dass die Rezepte so abgeändert werden das reines Kreuzen nicht reicht, sondern z.B. bei Erzen, der OreBlock vorhanden sein muss (also in dem Fall das nicht ein Eisenblock drunter sein muss sondern das Erz. (Bin mir aber gerade nicht sicher ob das nicht unmodifiziert im Prinzip eh so ist). Was ich im Prinzip sagen will, man muss seine Basis auch mal verlassen müssen ;)

**Comment by BakermanLP** [comment]
Agricraft ist nicht für 1.11.2 erhöltlich, die 1.10.2er Version war recht buggy, deswegen raus damit
