### ISSUE TITLE
Modpack Utils integration

### ISSUE THREAD

**Issue by ComBak-Webservices** [BakermanLP/ProjectRET-AoT#98]
Issue posted by Player867: Wenn ihr das lesen könnt, wurde ingame ein issue gepostet. :)

**Comment by DerOliDE** [comment]
TODO:
- [x] Multiline Description Text Field
- [x] Custom Main Menu integration
- [x] Translation de/en

**Comment by lordjoda** [comment]
Coole Sache!

**Comment by DerOliDE** [comment]
Danke wir werden immer professioneller. :D

Erste "Impressionen":
![mpu-changelog](https://user-images.githubusercontent.com/5699429/27283671-9f258096-54f5-11e7-8d90-9b341dcf5c95.png)
![mpu-bugreport](https://user-images.githubusercontent.com/5699429/27283677-a54b1c06-54f5-11e7-843e-fd85e24a2802.png)

Wünsche, Kritik, oder Verbesserungsvorschläge?

**Comment by BakermanLP** [comment]
Ui. Sieht gut aus.

Oliver <notifications@github.com> schrieb am Mo., 19. Juni 2017, 13:46:

**Comment by DerOliDE** [comment]
@BakermanLP ggf. noch checken, ob Du die aktuelle [Modpack-Webservices](https://github.com/combak/Modpack-Webservice) Version auf Deinem Webserver hast, bevor wir die Mod ins Modpack packen.

**Comment by DerOliDE** [comment]
Erste lauffähige Version mit noch ein paar Bugs/Glitches aber wenigstens etwas, was man mal ins nächste Update packen kann. :)
https://github.com/combak/Modpack-Utils/releases/tag/0.1.0-alpha

**Comment by DerOliDE** [comment]
Nächstes Update https://github.com/combak/Modpack-Utils/releases/tag/0.1.1-alpha

Die gröbsten Schnitzer sollten draußen sein, die nächste Version wird dann ein Usability Update.

**Comment by DerOliDE** [comment]
Wie im Discord bereits erwähnt bekannte Probleme:
- Cursor in der TextArea spinnt noch
- TextArea hat kein Ausschlusskriterium für die letzte Zeile.

Musste das ganze noch zippen, sonst nimmt er das hier nicht als Upload an: [modpackutils.zip](https://github.com/BakermanLP/ProjectRET-AoT/files/1505819/modpackutils.zip)

Darin sind sämtliche benötigten libs enthalten einschließlich meiner common und ui lib, sprich die müssen dann auch aus den mods Ordner entfernt werden.

**Comment by BakermanLP** [comment]
Lade und baue ein.

**Comment by BakermanLP** [comment]
Die Beiden sind unverändert, oder?
olis-common-library-1.11.2-0.2.0-2993aa8.jar
olis-ui-library-1.11.2-0.1.1-alpha-2993aa8.jar

**Comment by DerOliDE** [comment]
Die libs musst Du rauswerfen, die sind in diesem Fall alle in der Mod enthalten.

**Comment by BakermanLP** [comment]
OK. Habe ich jetzt geschnallt aufgrund des Anhangs "-all"

**Comment by DerOliDE** [comment]
Da in dem Modpack eh nur eine Mod von mir drin ist, wird es in Zukunft nur die all Variante geben, ist glaube ich für uns beide einfacher. :)

**Comment by BakermanLP** [comment]
Kurze Frage zur Config:
```
{
    "webservices" : {
        "enabled"   : true,
        "url"       : "https://webservice.bakermanlp.de/",
        "github" : {
            "enabled"       : true,
            "repository"    : "aot"
        }
    }
}
```
Passt das so?

**Comment by DerOliDE** [comment]
Bei der URL habe ich den hinteren Slash nicht drin gehabt "https://webservice.bakermanlp.de", kA wie empfindlich da Java oder Unirest ist, wenn irgendwo // auftaucht.

**Comment by DerOliDE** [comment]
Bin immer noch nicht damit fertig geworden, ein neuen Stand hinzubekommen, der mir nicht gänzlich die Haare zu Berge stehen lässt, aber es gibt ein neuen Zwischenstand. ^^
[modpackutils.zip](https://github.com/BakermanLP/ProjectRET-AoT/files/1524099/modpackutils.zip)

Gefixt und neu dazu gekommen:
- Der Curser wandert nun korrekt in der TextArea
- Text läuft in der TextArea nich mehr aus dem Rahmen.
- Changelog und Bug Report Button gibt es jetzt auch in GameMenu.

Bekannte Fehler:
- TextArea hat kein Ausschlusskriterium für die letzte Zeile, man sieht den Text zwar nicht mehr rauslaufen, aber man kann mehr schreiben als in die Area passt.
- Wenn man mit dem Cursor zurückläuft (linke Pfeiltaste), kommt es beim Zeilenumbruch zu einer StringIndexOutOfBoundsException. Das bekomme ich hoffentlich bis Montag noch fixen, ist imho noch das größte Problem.

**Comment by DerOliDE** [comment]
Lauffähige Version für die 1.12.2, die aber auch noch ein paar Macken hat. Die "-all" Variante enthält wieder alle dazugehörigen Libs.

https://github.com/combak/Modpack-Utils/releases/tag/0.2.0

**Comment by DerOliDE** [comment]
Achja für die 1.12.2 gibt es auch ein neues config file, dass hatte ich schon hochgeladen:
https://github.com/BakermanLP/ProjectRET-AoT/blob/1.11.2/config/modpackutils.cfg

Die json Variante kann dann gelöscht werden.

**Comment by DerOliDE** [comment]
Und schon die nächste Version, in der die gröbsten Schlitzer drausen sein sollten. :)
https://github.com/combak/Modpack-Utils/releases/tag/0.2.1

**Comment by BakermanLP** [comment]
Das können wir dann doch mal langsam schliessen, oder?
