### ISSUE TITLE
Hella testet

### ISSUE THREAD

**Issue by hellamie** [BakermanLP/ProjectRET-AoT#99]
Problem

1) Beim Abbauen mit der Hand bzw Ohne das Werkzeug bekommt man Pile of irgendwas oder Bretter..so weit so gut..aber wie soll ich einen bartbuilder bauen ohne Baumklotz?.

2)Ich kann keine Türe so schnell auf mein "haus" machen..ich brauche dafür erst eine säge....ist machbar aber nervend die ersten 5 nächte

3)Seit wann haben die Ollen  Monster so viel Hirn und Taktick beim Käpfen....Pfui

**Comment by BakermanLP** [comment]
1) das ist noch falsch konfiguriert. Das sollte nicht so sein. 
2) Wird durch die Umstellung von 1 erledigt
3) Das sind die Einstellungen, die dein Mann gemacht hat :) Und die sind schon abgeschwächt. Das fördert meiner Meinung nach das Gruppenspiel in den ersten Nächten / Tagen

**Comment by hellamie** [comment]
so habe heute morgen noch mal in Ruhe, ohne Kinder, im singelplayer angefangen.

Wenn man genug Flint findet kann man sich eine einfache Axt craften und dan alle Tinkertische.  
Mit Slaps zugemachte Höhlenfronten lassen genug Licht ein, so das man nicht an Panik stirbt.

**Comment by Grambosch** [comment]
Ich steck im Loch fest weil im Sprung keine Blöcke gesetzt werden ^^ Picke kaputt SPiel zu Ende :)

**Comment by BakermanLP** [comment]
Das ist quasi ein ähnlicher Fehler, den Hellami schon gemeldet hatte. Ich
versuche für nächste Woche eine neue Version raus zu bringen, die wieder in
Richtung Release geht

Grambosch <notifications@github.com> schrieb am Do., 6. Juli 2017, 19:06:

**Comment by BakermanLP** [comment]
Das sollte nun alles funktionieren. Also Close
